package rules0

import tercerhombre.personaje.Personaje;

rule "martins anna cementerio"
    when
        martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.CEMENTERIO  )
        anna : Personaje( nombre == Personaje.anna, ubicacion == Ubicacion.CEMENTERIO  )
    then
        System.out.println("martins conoce a anna");  
end

rule "Personaje muerto"
    when
        p : Personaje( estadoSalud == EstadoSalud.MUERTO )
    then
        System.out.println( "Personaje muerto: " + p.getNombre() + " " + p.getActo());
end
