package rules

import tercerhombre.personaje.Personaje;
import tercerhombre.propiedades.*;
import tercerhombre.io.Buffer;
import tercerhombre.Fin;

/*
* -------------------------------------------------------------------
* ######################## ALTERNATIVAS ############################
* -------------------------------------------------------------------
*/


rule "lime esta vivo y martins encuentra a lime" 

// **************** METADATOS ******************* //
  @ruleDate(2016-12-10)

  @ruleDescription("En caso de que Lime esté vivo, cuando Martins llegue a casa de Lime lo encontrará y trabajará para él. ")

  @ruleAuthor(Adrián Egea)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //

agenda-group "g0"
no-loop true
    when
        martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.CASALIME, estadoSalud == EstadoSalud.VIVO  )
        lime : Personaje( nombre == Personaje.lime, estadoSalud == EstadoSalud.VIVO )
        
       	b : Buffer()
    then

	modify(b){
		append(Personaje.martins+" encuentra a Lime y trabaja para él. ");
	};
	
	insert(new Fin());
    	
end

rule "martins muere" 

// **************** METADATOS ******************* //
  @ruleDate(2016-12-10)

  @ruleDescription("En el caso de que Martins esté muerto, no hay historia que contar. ")

  @ruleAuthor(Adrián Egea)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //

agenda-group "g0"
no-loop true
    when
    	martins : Personaje(nombre == Personaje.martins , estadoSalud == EstadoSalud.MUERTO  )
    
        b : Buffer()
    then
    	modify(b){
			append(Personaje.martins+" esta "+martins.getEstadoSalud()+". ");
		}
		
		insert(new Fin());
end

rule "karl muere" 

// **************** METADATOS ******************* //
  @ruleDate(2016-12-10)

  @ruleDescription("En caso de que Karl este muerto, Martins no encontrará a nadie al ir a casa de Lime y volverá a EEUU. ")
  
  @ruleAuthor(Adrián Egea)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //

agenda-group "g0"
no-loop true
    when
    	karl : Personaje( nombre == Personaje.karl, estadoSalud == EstadoSalud.MUERTO  )
    
        b : Buffer()
    then
    	modify(b){
			append(Personaje.karl+" esta "+karl.getEstadoSalud()+". ");
			// TODO: como sigue ??
		}
		
		insert(new Fin());
end

        