//created on: 08-dic-2016
package rules

//list any import classes here.

import tercerhombre.personaje.Personaje;
import tercerhombre.propiedades.*;
import tercerhombre.io.Buffer;



rule "Lime hace acto de presencia" agenda-group "g5"
no-loop true
	when
		lime : Personaje ( nombre == Personaje.lime, estadoSalud == EstadoSalud.MUERTO )
		martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.CASAANNA )
		
		b : Buffer()
	then

		modify(lime){
			setEstadoSalud(EstadoSalud.VIVO);
		}		
		modify(b){
			append(Personaje.lime+" le aparece a Martins en la calle. ");
		};
		modify(lime){
			setUbicacion(Ubicacion.PLAZA);
		}
		modify(martins){
			setUbicacion(Ubicacion.PLAZA);
		}		
		modify(b){
			append(Personaje.lime+" y Martins llegan a"+lime.getUbicacion().toString());
		};
		modify(lime){
			setUbicacion(Ubicacion.CLOACAS);
		};
		modify(b){
			append(Personaje.lime+" desaparece, se esconde y va a"+lime.getUbicacion().toString()+". ");
		};
		
		
end

rule "Calloway va a la Plaza" agenda-group "g5"
no-loop true
	when
		calloway : Personaje (nombre == Personaje.calloway, ubicacion == Ubicacion.COMISARIA )
		lime : Personaje ( nombre == Personaje.lime, estadoSalud == EstadoSalud.VIVO )
		
		b : Buffer()	
	then
		modify(calloway){
			setUbicacion(Ubicacion.PLAZA);
		}	
		modify(b){
			append(Personaje.calloway+" va a"+calloway.getUbicacion().toString());
		};
	
end

rule "Paine va a la Plaza" agenda-group "g5"
no-loop true
	when
		paine : Personaje (nombre == Personaje.paine, ubicacion == Ubicacion.COMISARIA )
		b : Buffer()
	then
		modify(paine){
			setUbicacion(Ubicacion.PLAZA);
		}	
		modify(b){
			append(Personaje.paine+" va a"+paine.getUbicacion().toString());
		};
	
end

rule "Calloway y Martins buscan a Lime en las cloacas" agenda-group "g5"
	no-loop true
	when
		martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.PLAZA )
		calloway : Personaje (nombre == Personaje.calloway, ubicacion == Ubicacion.PLAZA )		
		
		b : Buffer()
	then
		modify(calloway){
			setUbicacion(Ubicacion.CLOACAS);
		}		

		modify(martins){
			setUbicacion(Ubicacion.CLOACAS);
		}

		modify(b){
			append(Personaje.martins+" y Calloway buscan a Lime en"+calloway.getUbicacion().toString()+". ");
		};
	
end

rule "Paine esta con calloway en las cloacas" agenda-group "g5"
	no-loop true
	when
		paine : Personaje (nombre == Personaje.paine, ubicacion == Ubicacion.PLAZA,	
							estadoSalud == EstadoSalud.VIVO )
		b : Buffer()
		
	then
		modify(paine){
			setUbicacion(Ubicacion.CLOACAS);
		}
		
		modify(b){
			append(Personaje.paine+" está con Martins y Calloway y buscan a Lime en"+paine.getUbicacion().toString()+". ");
		};
	
end

rule "Harbin esta enterrado en la tumba de Lime" agenda-group "g5"
    no-loop true
    when
		martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.CLOACAS )
		calloway : Personaje (nombre == Personaje.calloway, ubicacion == Ubicacion.CLOACAS )
		harbin : Personaje (nombre == Personaje.harbin)
		
		b : Buffer()
    then
        modify(calloway){
			setUbicacion(Ubicacion.CEMENTERIO);
		}
		modify(martins){
			setUbicacion(Ubicacion.CEMENTERIO);
		}
	
		modify(b){
			append(Personaje.calloway+" y Martins van a"+calloway.getUbicacion().toString());
		};
		
		modify(harbin){
			setUbicacion(Ubicacion.CEMENTERIO);
		}
		
		modify(harbin){
			setEstadoSalud(EstadoSalud.MUERTO);
		}
		
		modify(b){
			append("Encuentran el cadáver de Harbin en la tumba de Lime");
		};
end

rule "Paine esta en el cementerio también" agenda-group "g5"
	no-loop true
    when
    	paine : Personaje (nombre == Personaje.paine, ubicacion == Ubicacion.PLAZA )
    	b : Buffer()
    	
    then	
		modify(paine){
			setUbicacion(Ubicacion.CEMENTERIO);
		}
		modify(b){
			append("Paine va a"+paine.getUbicacion().toString()+" con Calloway y Martins");
		};
 
end

rule "Llevan a Anna a la comisaria" agenda-group "g5"
    no-loop true
    when
		martins : Personaje (nombre == Personaje.martins, ubicacion == Ubicacion.CEMENTERIO )
		anna : Personaje (nombre == Personaje.anna, nacionalidad != Nacionalidad.AUSTRIA )
		lime : Personaje (nombre == Personaje.lime)
		calloway : Personaje (nombre == Personaje.calloway, ubicacion == Ubicacion.CEMENTERIO )
		harbin : Personaje (nombre == Personaje.harbin, estadoSalud == EstadoSalud.MUERTO )
		
		b : Buffer()
    then
        modify(anna){
			setUbicacion(Ubicacion.COMISARIA);
		}
		modify(martins){
			setUbicacion(Ubicacion.COMISARIA);
		}
		modify(calloway){
			setUbicacion(Ubicacion.COMISARIA);
		}
		modify(anna){
   		getBusca_a().add(lime);
		};
	
		modify(b){
			append("Llevan a Anna a"+anna.getUbicacion().toString()+" por su pasaporte falso. ").
			append(Personaje.martins+" le dice a Anna que ha visto a Lime. ").
			append(Personaje.calloway+" le pide ayuda a Anna para encontrar a Lime y ella lo rechaza. ").
			append(Personaje.anna+" busca a Lime. ");
		};
		
end

rule "Martins va al Sector Ruso a hablar con Lime" agenda-group "g5"
    no-loop true
    when
		martins : Personaje (nombre == Personaje.martins, ubicacion == Ubicacion.COMISARIA )
		lime : Personaje (nombre == Personaje.lime, ubicacion == Ubicacion.CLOACAS)
		tercerhombre : Personaje (nombre == Personaje.tercerhombre)
		
		b : Buffer()
	then
	
        modify(martins){
			setUbicacion(Ubicacion.SECTORRUSO);
		}
		modify(lime){
			setUbicacion(Ubicacion.SECTORRUSO);
		}

		modify(b){
			append(Personaje.martins+" va a"+martins.getUbicacion().toString()+" para buscar a Lime. ");
		};
		
		modify(martins){
			setUbicacion(Ubicacion.NORIA);
		}
		modify(lime){
			setUbicacion(Ubicacion.NORIA);	
		}
		
		modify(b){
			append(Personaje.martins+" y Lime hablan en "+martins.getUbicacion().toString()+". ");
		};
		
		modify(tercerhombre) {
			setNombre(Personaje.lime);
		}
		
		modify(b){
			append("En la conversación se confirma que el tercer hombre es "+tercerhombre.getNombre()+". ");
		};
		
end

rule "Kurtz esta con Lime" agenda-group "g5"
    no-loop true
    when
    	lime : Personaje (nombre == Personaje.lime, ubicacion == Ubicacion.SECTORRUSO)
		tercerhombre : Personaje (nombre == Personaje.tercerhombre)
		kurtz : Personaje (nombre == Personaje.kurtz)
		b : Buffer()    
    then
    	modify(kurtz){
			setUbicacion(Ubicacion.SECTORRUSO);
		}
		modify(b){
			append(Personaje.kurtz+" está en e"+kurtz.getUbicacion().toString()+" junto con Lime. ");
		};

end

rule "Winkel esta con Lime" agenda-group "g5"
    no-loop true
    when
    	lime : Personaje (nombre == Personaje.lime, ubicacion == Ubicacion.SECTORRUSO)
		tercerhombre : Personaje (nombre == Personaje.tercerhombre)
		winkel : Personaje (nombre == Personaje.winkel)
		b : Buffer()    
    then
    	modify(winkel){
			setUbicacion(Ubicacion.SECTORRUSO);
		}
		
		modify(b){
			append(Personaje.winkel+" está en e"+winkel.getUbicacion().toString()+" junto con Lime. ");
		};
end

rule "Martins decide ayudar a Calloway" agenda-group "g5"
    no-loop true
    when
		martins : Personaje (nombre == Personaje.martins, ubicacion == Ubicacion.NORIA )
		calloway : Personaje (nombre == Personaje.calloway )
		paine : Personaje (nombre == Personaje.paine )
		
		b : Buffer()
    then
        modify(martins){
			setUbicacion(Ubicacion.COMISARIA);
		}
		modify(calloway){
			setUbicacion(Ubicacion.COMISARIA);
		}

	
		modify(b){
			append(Personaje.martins+", Calloway se reunen en "+martins.getUbicacion().toString()+". ");
		};
end

rule "Paine esta con ellos" agenda-group "g5"
no-loop true
    when
		martins : Personaje (nombre == Personaje.martins, ubicacion == Ubicacion.COMISARIA )
		lime : Personaje (nombre == Personaje.lime, ubicacion == Ubicacion.NORIA )
		paine : Personaje (nombre == Personaje.paine )
		
		b : Buffer()
    then
		modify(paine){
			setUbicacion(Ubicacion.COMISARIA);
		}
		modify(b){
			append(Personaje.paine+" acompaña a Martins y Calloway en"+paine.getUbicacion().toString()+". ");
		};

end

rule "Decide ayudarle a cambio de billete para Anna" agenda-group "g5"
    no-loop true
    when
    	martins : Personaje (nombre == Personaje.martins, ubicacion == Ubicacion.COMISARIA )
		calloway : Personaje (nombre == Personaje.calloway, ubicacion == Ubicacion.COMISARIA )
		anna : Personaje (nombre == Personaje.anna, estadoSalud == EstadoSalud.VIVO,
							 nacionalidad != Nacionalidad.AUSTRIA )
		b : Buffer()
    then
		modify(b){
			append(Personaje.martins+" cede a ayudar a Calloway a atrapar a Lime si él lleva a Anna de vuelta a Rusia. ");
		};
		    	
    
end

rule "Martins y Anna discuten en la estacion" agenda-group "g5"
    no-loop true
    when
		martins : Personaje (nombre == Personaje.martins, ubicacion == Ubicacion.COMISARIA )
		anna : Personaje (nombre == Personaje.anna, estadoSalud == EstadoSalud.VIVO )
		lime : Personaje (nombre == Personaje.lime, ubicacion == Ubicacion.NORIA )
		
		
		b : Buffer()
    then
        modify(martins){
			setUbicacion(Ubicacion.ESTACION);
		}
		modify(anna){
			setUbicacion(Ubicacion.ESTACION);
		}
		
		modify(anna){
    		getEnfrentado_con().add(martins);
    	};

		modify(anna){
			getAmigo_de().remove(martins);
		};
	
		modify(b){
			append(Personaje.martins+" espera en "+martins.getUbicacion().toString()+" a que Anna coja el tren. ").
			append(Personaje.anna+" llega a"+anna.getUbicacion().toString()+" y ve a Martins .").
			append(Personaje.anna+" y Martins discuten y Anna decide no coger el tren. ").
			append(Personaje.anna+" está enfrentada con Martins. ");
			
		};
end

// SUCEDE POR QUE ANNA LE HACE DUDAR
rule "Martins y Calloway van al hospital" agenda-group "g5"
	no-loop true
	when
		martins : Personaje (nombre == Personaje.martins, ubicacion == Ubicacion.ESTACION )
		calloway : Personaje (nombre == Personaje.calloway )
				
		b : Buffer()

    then
        modify(martins){
			setUbicacion(Ubicacion.COMISARIA);
		}
		modify(calloway){
			setUbicacion(Ubicacion.COMISARIA);
		}
	
		modify(b){
			append(Personaje.martins+" habla con Calloway en"+martins.getUbicacion().toString()+" y duda.");
		};
		
		modify(martins){
			setUbicacion(Ubicacion.HOSPITAL);
		}
		modify(calloway){
			setUbicacion(Ubicacion.HOSPITAL);
		}

		modify(b){
			append(Personaje.calloway+" lleva a Martins a"+martins.getUbicacion().toString()+" y convence a Martins para que le ayude.");
		};		
end

rule "Martins y Lime se ven en el cafe" agenda-group "g5"
	no-loop true
	when
		martins : Personaje (nombre == Personaje.martins, ubicacion == Ubicacion.HOSPITAL )
		calloway : Personaje (nombre == Personaje.calloway )
		lime : Personaje (nombre == Personaje.lime )
		
		b : Buffer()

    then
        modify(martins){
			setUbicacion(Ubicacion.CAFEMARC);
		}
		modify(calloway){
			setUbicacion(Ubicacion.CAFEMARC);
		}
	
		modify(b){
			append(Personaje.martins+" queda con Lime en e"+martins.getUbicacion().toString()+". ").
			append(Personaje.calloway+" esta fuera esperando la llegada de Lime. ");			
		};

end

rule "Paine esta en el Café Marc" agenda-group "g5"
	no-loop true
	when
		paine : Personaje (nombre == Personaje.paine )
		martins : Personaje (nombre == Personaje.martins, ubicacion == Ubicacion.CAFEMARC )	
		calloway : Personaje (nombre == Personaje.calloway, ubicacion == Ubicacion.CAFEMARC )	
		b : Buffer()

	then
		modify(paine){
			setUbicacion(Ubicacion.CAFEMARC);
		}
		modify(b) {
			append(Personaje.paine+" está con Calloway fuera de e"+paine.getUbicacion().toString()+" esperando a Lime. ");
		};
end


rule "Lime va al Café Marc" agenda-group "g5"
	no-loop true
	when
		lime : Personaje (nombre == Personaje.lime )
		martins : Personaje (nombre == Personaje.martins, ubicacion == Ubicacion.CAFEMARC )			
		b : Buffer()

	then
		modify(lime){
			setUbicacion(Ubicacion.CAFEMARC);
		}
		modify(b) {
			append(Personaje.lime+" aparece en e"+lime.getUbicacion().toString()+". ");
		};
end

rule "Anna va al Café Marc" agenda-group "g5"
	no-loop true
	when
		anna : Personaje (nombre == Personaje.anna )
		lime : Personaje (nombre == Personaje.lime, ubicacion == Ubicacion.CAFEMARC )			
		b : Buffer()

	then
		modify(anna){
			setUbicacion(Ubicacion.CAFEMARC);
		}
		modify(b) {
			append(Personaje.anna+" está en e"+anna.getUbicacion().toString()+". ").
			append(Personaje.anna+" le dice a Lime que huya. ");
		};
end

rule "Desenlace en las cloacas" agenda-group "g5"
	no-loop true
	when
		martins : Personaje (nombre == Personaje.martins, ubicacion == Ubicacion.CAFEMARC )
		calloway : Personaje (nombre == Personaje.calloway )
		lime : Personaje (nombre == Personaje.lime )

		b : Buffer()
    then
        modify(martins){
			setUbicacion(Ubicacion.CLOACAS);
		}
		modify(calloway){
			setUbicacion(Ubicacion.CLOACAS);
		}

		modify(lime){
			setUbicacion(Ubicacion.CLOACAS);
		}
	
		modify(b){
			append(Personaje.lime+" huye a"+lime.getUbicacion().toString()+"y Martins y Calloway le persiguen. ");
		};
end

rule "Paine está" agenda-group "g5"
	no-loop true
	when
		martins : Personaje (nombre == Personaje.martins, ubicacion == Ubicacion.CLOACAS )
		calloway : Personaje (nombre == Personaje.calloway, ubicacion == Ubicacion.CLOACAS )
		paine : Personaje (nombre == Personaje.paine, estadoSalud == EstadoSalud.VIVO )

		b : Buffer()
	
	then
	
		modify(paine){
			setUbicacion(Ubicacion.CLOACAS);
		}
		modify(b) {
			append("Paine está con Calloway y Martins en las Cloacas buscando a Lime. ");	
		};

end

rule "Muere Lime" agenda-group "g5"
	no-loop true
	when
		martins : Personaje (nombre == Personaje.martins, ubicacion == Ubicacion.CLOACAS )
		lime : Personaje (nombre == Personaje.lime, ubicacion == Ubicacion.CLOACAS )
		b : Buffer()
	
	then
		modify(b) {
			append("Calloway y Martins encuentran a Lime y Martins mata a Lime. ");	
		};
		
		modify(lime){
			setEstadoSalud(EstadoSalud.MUERTO);
		}
		modify(lime){
			setUbicacion(Ubicacion.CEMENTERIO);
		}	
	
end

rule "Final" agenda-group "g5"
	no-loop true
	when
		martins : Personaje (nombre == Personaje.martins, ubicacion == Ubicacion.CLOACAS )
		calloway : Personaje (nombre == Personaje.calloway )
		lime : Personaje (nombre == Personaje.lime, estadoSalud == EstadoSalud.MUERTO )
		
		b : Buffer()
    then
        modify(martins){
			setUbicacion(Ubicacion.CEMENTERIO);
		}
		modify(calloway){
			setUbicacion(Ubicacion.CEMENTERIO);
		}
	
		modify(b){
			append(Personaje.martins+" y Calloway van a"+martins.getUbicacion().toString()+" al entierro de Lime. ");
		};
end

rule "Anna esta en el final" agenda-group "g5"
	no-loop true
	when
		anna : Personaje (nombre == Personaje.anna, estadoSalud == EstadoSalud.VIVO )
		martins : Personaje (nombre == Personaje.martins, ubicacion == Ubicacion.CEMENTERIO )
		b : Buffer()
		
	then
		modify(anna){
			setUbicacion(Ubicacion.CEMENTERIO);
		}
		modify(b){
			append(Personaje.anna+"está en e"+anna.getUbicacion().toString()+". ").
			append(Personaje.anna+" ignora a Martins.");	
		};
end

rule "Paine esta en el final" agenda-group "g5"
	no-loop true
	when
		paine : Personaje (nombre == Personaje.paine, estadoSalud == EstadoSalud.VIVO )
		martins : Personaje (nombre == Personaje.martins, ubicacion == Ubicacion.CEMENTERIO )
		b : Buffer()
	
	then
		modify(paine){
			setUbicacion(Ubicacion.CEMENTERIO);
		}
		modify(b){
			append(Personaje.paine +" está en e"+paine.getUbicacion().toString()+". ");
		};
end

