package rules

import tercerhombre.personaje.Personaje;
	
rule "martins karl" agenda-group "g0"
    when
        martins : Personaje( nombre == Personaje.martins  )
        karl : Personaje( nombre == Personaje.karl  )
        
        not Personaje( nombre == Personaje.martins ) from karl.conoce_a
        not Personaje( nombre == Personaje.karl ) from martins.conoce_a
    then
        modify(martins){
		   getConoce_a().add(karl);
		};
		modify(karl){
		   getConoce_a().add(martins);
		};
		
		Main.print("Martins conoce a "+Personaje.karl+". ");
        Main.print("Karl conoce a "+Personaje.martins+". ");
		
end 

