//created on: 07-dic-2016
package rules

import tercerhombre.personaje.Personaje;
import tercerhombre.propiedades.*;
import tercerhombre.io.Buffer;


//TODO Revisar el orden de las reglas Y falta poner los append

rule "kurtz y  martins van casa lime" agenda-group "g2"

    when
    	martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.CAFEMOZART )
        kurtz : Personaje( nombre == Personaje.kurtz, ubicacion == Ubicacion.CAFEMOZART )
        winkel : Personaje( nombre == Personaje.winkel)
        anna : Personaje( nombre == Personaje.anna)
        popescu : Personaje( nombre == Personaje.popescu)
        karl : Personaje( nombre == Personaje.karl)
        
    then
    
    	insert(Personaje.nuevo().
    	setNombre(Personaje.anna).
    	setGenero(Genero.MUJER).
    	setActividad(ActividadLegal.ACTRIZ).
    	setEstadoSalud(EstadoSalud.VIVO).
    	setNacionalidad(null).
    	setUbicacion(null));
    	
    	//Insertamos a Winkel
    	
    	insert(Personaje.nuevo().
    	setNombre(Personaje.winkel).
    	setGenero(Genero.HOMBRE).
    	setActividad(ActividadLegal.MEDICO).
    	setEstadoSalud(EstadoSalud.VIVO).
    	setNacionalidad(null).
    	setUbicacion(null));
    	
    	modify(winkel){
    	 getConoce_a().add(lime);
    	};	

		modify(winkel){
    		getAmigo_de().add(lime);
    	};	

		modify(winkel){
    		getConoce_a().add(kurtz);
    	};	

		modify(lime){
    		getAmigo_de().add(winkel);
    	};	

		modify(lime){
    		getConoce_a().add(winkel);
    	};
	
		modify(kurtz){
    		getConoce_a().add(winkel);
    	};	
    	
    	insert(Personaje.nuevo().
    	setNombre(Personaje.popescu).
    	setGenero(Genero.HOMBRE).
    	setActividad(Actividad.desconocida).
    	setEstadoSalud(EstadoSalud.VIVO).
    	setNacionalidad(Nacionalidad.RUMANO).
    	setUbicacion(null));
    	
		//insertamos popescu
	modify(popescu){
    		getConoce_a().add(lime);
    	};	

	modify(popescu){
    		getAmigo_de().add(lime);
    	};	

	modify(popescu){
    		getConoce_a().add(kurtz);
    	};

	modify(popescu){
    		getAmigo_de().add(kurtz);
    	};	

	modify(lime){
    		getAmigo_de().add(popescu);
    	};	

	modify(lime){
    		getConoce_a().add(popescu);
    	};
	
	modify(kurtz){
    		getConoce_a().add(popescu);
    	};

	modify(kurtz){
    		getAmigo_de().add(popescu);
    	};
    
        modify(kurtz){
		setUbicacion(Ubicacion.CASALIME);
		};
		modify(martins){
		setUbicacion(Ubicacion.CASALIME);
		};
		modify(martins){
    		getBusca_a().add(anna);
    	};
    	modify(karl){
    	getConoce_a().add(kurtz);
    	}
		//Insertamos de anna 
		modify(anna){
				setUbicacion(Ubicacion.CASANOVACLUB);
			};

		modify(anna){
	    		getConoce_a().add(lime);
	    	};
		modify(kurtz){
	    		getConoce_a().add(anna);
	    	};
		modify(lime){
	    		getConoce_a().add(anna);
	    	};
	    modify(martins){
	    		getBusca_a().add(anna);  //TODO hay que quitarlo despues?

end


rule "visita a anna" agenda-group "g2" // 
	when
    	martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.CASALIME )
    	anna : Personaje( nombre == Personaje.anna , ubicacion == Ubicacion.CASANOVACLUB)
    then
    
     	modify(martins){
	    setUbicacion(Ubicacion.CASANOVACLUB);
	    };
	    
	     modify(martins){
	    		getConoce_a().add(anna);
	    };
	    
	    modify(anna){
	    		getConoce_a().add(martins);
	    };
	    
	    modify(anna){
    		getQuiere_a().add(lime);  //TODO sabemos si lime quiere a anna?
    	};
    	
    	
	    
end

 rule "vuelta a casa Lime" agenda-group "g2"
	when
    	martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.CASANOVACLUB )
        anna : Personaje( nombre == Personaje.anna , ubicacion == Ubicacion.CASANOVACLUB)
        karl : Personaje( nombre == Personaje.karl)
    then 
    	
    	modify(martins){
	    setUbicacion(Ubicacion.CASALIME);
	    };
	    modify(anna){
	    setUbicacion(Ubicacion.CASALIME);
	    };
	    modify(anna){
	    		getConoce_a().add(karl);
	    };
	    modify(karl){
	    		getConoce_a().add(anna);
	    };
	    
    	
    
end

rule "martins y anna van a casa de anna" agenda-group "g2"
	when
    	martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.CASALIME )
      	anna : Personaje( nombre == Personaje.anna , ubicacion == Ubicacion.CASALIME)
    then
    
    modify(anna){
	    setUbicacion(Ubicacion.CASAANNA);
	    };
	    modify(martins){
	    setUbicacion(Ubicacion.CASAANNA);
	    };
	    
	    
    
end    