package rules

import tercerhombre.personaje.Personaje;

rule "blablabla" agenda-group "g1"
    when
        martins : Personaje( nombre == Personaje.martins  )
        karl : Personaje( nombre == Personaje.karl  )
        
        not Personaje( nombre == Personaje.martins ) from karl.conoce_a
        not Personaje( nombre == Personaje.karl ) from martins.conoce_a
    then
        System.out.println("HOLAAAAAAAAAAAAAA"); 
end 

