package rules

import tercerhombre.personaje.Personaje;
import tercerhombre.Buffer;
	
rule "martins karl" agenda-group "g0"
no-loop true
    when
        martins : Personaje( nombre == Personaje.martins  )
        karl : Personaje( nombre == Personaje.karl  )
        lime : Personaje( nombre == Personaje.lime  )
        
       	b : Buffer()
    then
        modify(martins){
		   getConoce_a().add(karl);
		};
		modify(karl){
		   getConoce_a().add(martins);
		};
		modify(karl){
		   getConoce_a().add(lime);
		};
		modify(lime){
		   getConoce_a().add(karl);
		};
		
		
		modify(b){
			append("Martins conoce a "+Personaje.karl+". ").
	        append("Karl conoce a "+Personaje.martins+". ").
	        append("Karl conoce a "+Personaje.lime+". ").
	        append("Lime conoce a "+Personaje.karl+". ");
		};
		
		
end 

