package rules

import tercerhombre.personaje.Personaje;
import tercerhombre.Main;
	
rule "martins karl" agenda-group "g0"
no-loop true
    when
        martins : Personaje( nombre == Personaje.martins  )
        karl : Personaje( nombre == Personaje.karl  )
        lime : Personaje( nombre == Personaje.lime  )
        
       
    then
        modify(martins){
		   getConoce_a().add(karl);
		};
		modify(karl){
		   getConoce_a().add(martins);
		};
		modify(karl){
		   getConoce_a().add(lime);
		};
		modify(lime){
		   getConoce_a().add(karl);
		};
		
		Main.print("Martins conoce a "+Personaje.karl+". ");
        Main.print("Karl conoce a "+Personaje.martins+". ");
        Main.print("Karl conoce a "+Personaje.lime+". ");
        Main.print("Lime conoce a "+Personaje.karl+". ");
		
end 

