//created on: 11-dic-2016
package rules

import tercerhombre.personaje.Personaje;
import tercerhombre.propiedades.*;
import tercerhombre.io.Buffer;

rule "problemas en casa de anna" 

// **************** METADATOS ******************* //
  @ruleDate(2016-12-05)

  @ruleDescription("Calloway va a casa de Anna por que tiene problemas con su pasaporte estando Martins allí.")

  @ruleAuthor(Pablo Saura)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //


agenda-group "g3"
no-loop true
	when
    	martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.CASAANNA )
        anna : Personaje( nombre == Personaje.anna, ubicacion == Ubicacion.CASAANNA, nacionalidad != Nacionalidad.AUSTRIA )
        calloway : Personaje( nombre == Personaje.calloway )
        
        not Personaje( nombre == Personaje.calloway ) from anna.conoce_a 

        b : Buffer()

    then
// 
    	 modify(calloway){
	    	setUbicacion(Ubicacion.CASAANNA);
	    };

      modify(anna){
	    	getConoce_a().add(calloway)
	    };

	    modify(calloway){
	    	getConoce_a().add(anna)
	    };

	    modify(martins){
    		getEnfrentado_con().add(calloway);
    	};


    	modify(b){
			append(Personaje.martins+" va a"+martins.getUbicacion().toString()+". ").
			append(Personaje.anna+" conoce a "+Personaje.calloway+". ").
			append(Personaje.calloway+" conoce a "+Personaje.anna+". ").
			append(Personaje.martins+" enfrentado con "+Personaje.calloway+". ");

		};

end

rule "anna conoce a paine en su casa" 

// **************** METADATOS ******************* //
  @ruleDate(2016-12-05)

  @ruleDescription("Paine ha ido con Calloway a casa de Anna.")

  @ruleAuthor(Pablo Saura)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //

agenda-group "g3"
no-loop true
	when
		martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.CASAANNA )
		anna : Personaje( nombre == Personaje.anna, ubicacion == Ubicacion.CASAANNA, nacionalidad != Nacionalidad.AUSTRIA )
        paine : Personaje( nombre == Personaje.paine, estadoSalud == EstadoSalud.VIVO )

		b : Buffer()
	then
// 

		modify(anna){
	    	getConoce_a().add(paine)
	    };

	    modify(paine){
	    	getConoce_a().add(anna)
	    };

	    modify(paine){
	    	setUbicacion(Ubicacion.CASAANNA);
	    };

	    modify(martins){
    		getEnfrentado_con().add(paine);
    	};

    	modify(b){
    		append(Personaje.paine+" va a"+paine.getUbicacion().toString()+". ").
    		append(Personaje.anna+" conoce a "+Personaje.paine+". ").
    		append(Personaje.paine+" conoce a "+Personaje.anna+". ").
    		append(Personaje.martins+" enfrentado con "+Personaje.paine+". ");
    	}
end


 rule "van a la comisaria " 
 
 // **************** METADATOS ******************* //
  @ruleDate(2016-12-05)

  @ruleDescription("Calloway y Paine deciden llevar a Anna a la comisaria.")

  @ruleAuthor(Pablo Saura)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //
 
 agenda-group "g3"
 no-loop true
	when
    	martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.CASAANNA )
        anna : Personaje( nombre == Personaje.anna, ubicacion == Ubicacion.CASAANNA )
        paine : Personaje( nombre == Personaje.paine, ubicacion == Ubicacion.CASAANNA )
        calloway : Personaje( nombre == Personaje.calloway, ubicacion == Ubicacion.CASAANNA )

				b : Buffer()

    then
// 
    	modify(calloway){
	    	setUbicacion(Ubicacion.COMISARIA);
	    };
	    modify(paine){
	    	setUbicacion(Ubicacion.COMISARIA);
	    };
	    modify(anna){
	    	setUbicacion(Ubicacion.COMISARIA);
	    };

			modify(b){
			append(Personaje.calloway+" va a"+calloway.getUbicacion().toString()+". ").
			append(Personaje.paine+" va a"+paine.getUbicacion().toString()+". ").
			append(Personaje.anna+" va a"+anna.getUbicacion().toString()+". ");
		};
end

rule "va a ver a winkel" 

// **************** METADATOS ******************* //
  @ruleDate(2016-12-05)

  @ruleDescription("Martins decide ir a cada del Dr Winkel a hablar con él.")

  @ruleAuthor(Pablo Saura)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //

agenda-group "g3"
no-loop true
	when
    	martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.CASAANNA || ubicacion == Ubicacion.CASALIME )
        winkel : Personaje( nombre == Personaje.winkel, estadoSalud == EstadoSalud.VIVO )

				b : Buffer()

    then
// 

      	modify(winkel){
			setUbicacion(Ubicacion.CASAWINKEL);
		};
		modify(martins){
			setUbicacion(Ubicacion.CASAWINKEL);
		};

		modify(b){
		append(Personaje.winkel+" va a"+winkel.getUbicacion().toString()+". ").
		append(Personaje.martins+" va a"+martins.getUbicacion().toString()+". ");
	};

    end

rule "habla con Winkel" 

// **************** METADATOS ******************* //
  @ruleDate(2016-12-05)

  @ruleDescription("Martins y Winkel hablan sobre Lime y su muerte.")

  @ruleAuthor(Pablo Saura)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //

agenda-group "g3"  // para inseratar a Winkel primero martins tiene que ir
no-loop true
   when
    	martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.CASAWINKEL )
        winkel : Personaje( nombre == Personaje.winkel, ubicacion == Ubicacion.CASAWINKEL )

		not Personaje( nombre == Personaje.winkel ) from martins.conoce_a 

		b : Buffer()

    then
// 
    	modify(martins){
      		getConoce_a().add(winkel);
      	};

      	modify(winkel){
      		getConoce_a().add(martins);
      	};

				modify(b){
				append(Personaje.martins+" conoce a "+Personaje.winkel+". ").
				append(Personaje.winkel+" conoce a "+Personaje.martins+". ");
			};
end

rule "martins va al cassanovaclub" 
// **************** METADATOS ******************* //
  @ruleDate(2016-12-05)

  @ruleDescription("Martins va al Cassanova Club para hablar con Kurtz, ya que el trabaja allí.")

  @ruleAuthor(Pablo Saura)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //

agenda-group "g3"
no-loop true
   when
    	martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.CASAWINKEL || ubicacion == Ubicacion.CASAANNA || ubicacion == Ubicacion.CASALIME )
        kurtz : Personaje( nombre == Personaje.kurtz )
        

				b : Buffer()

    then
// 


		modify(kurtz){
			setUbicacion(Ubicacion.CASANOVACLUB);
		};

		
		modify(martins){
			setUbicacion(Ubicacion.CASANOVACLUB);
		};

		

		modify(b){
			append(Personaje.kurtz+" va a"+kurtz.getUbicacion().toString()+". ").
			append(Personaje.martins+" va a"+martins.getUbicacion().toString()+". ");
		};
end

rule "martins conoce a popescu en cassanovaclub" 
// **************** METADATOS ******************* //
  @ruleDate(2016-12-05)

  @ruleDescription("Kurtz aprovecha para presentarle a Martins a Popescu ya que estaba en el Club.")

  @ruleAuthor(Pablo Saura)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //

agenda-group "g3"
no-loop true
   when
   	popescu : Personaje( nombre == Personaje.popescu, estadoSalud == EstadoSalud.VIVO )
   	martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.CASANOVACLUB)
   	tercerhombre : Personaje( nombre == Personaje.tercerhombre )
   	
   	b: Buffer()
   then
   		modify(popescu){
			setUbicacion(Ubicacion.CASANOVACLUB);
		};
		
		modify(popescu){
    		getSospecha_de().add(martins);
    	};

    	modify(martins){
    		getConoce_a().add(popescu);
    	};

		modify(popescu){
    		getConoce_a().add(martins);
    	};

    	modify(martins){
    		getBusca_a().add(tercerhombre);
    	};
    	
    	modify(b){
    		append(Personaje.popescu+" va a"+popescu.getUbicacion().toString()+". ").
    		append(Personaje.martins+" conoce a "+Personaje.popescu+". ").
			append(Personaje.popescu+" conoce a "+Personaje.martins+". ").
    		append(Personaje.popescu+" sospecha de "+Personaje.martins+". ").
			append(Personaje.martins+" busca a "+Personaje.tercerhombre+". ");
    	};
   	
 end


 rule "anna está en casanova club" 
 // **************** METADATOS ******************* //
  @ruleDate(2016-12-05)

  @ruleDescription("Martins encuentra a Anna en el Cassanova Club y se quedan juntos.")

  @ruleAuthor(Pablo Saura)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //
 
 agenda-group "g3"  // para inseratar a Winkel primero martins tiene que ir
no-loop true
   when
   		martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.CASANOVACLUB )
   		popescu : Personaje( nombre == Personaje.popescu, estadoSalud == EstadoSalud.VIVO)
   		kurtz : Personaje( nombre == Personaje.kurtz )
   		anna : Personaje( nombre == Personaje.anna, ubicacion == Ubicacion.COMISARIA, estadoSalud == EstadoSalud.VIVO )

   		b : Buffer()
   	then
// 

   		modify(anna){
    		getConoce_a().add(kurtz);
    	};

		modify(anna){
    		getConoce_a().add(popescu);
    	};

    	modify(anna){
			setUbicacion(Ubicacion.CASANOVACLUB);
		};

		modify(b){
			append(Personaje.anna+" va a"+anna.getUbicacion().toString()+". ").
			append(Personaje.anna+" conoce a "+Personaje.kurtz+". ").
			append(Personaje.anna+" conoce a "+Personaje.popescu+". ").
			append(Personaje.popescu+" conoce a "+Personaje.anna+". ");
		}
 end

rule "crabbin está en casanova club" 
// **************** METADATOS ******************* //
  @ruleDate(2016-12-05)

  @ruleDescription("Crabbin saluda a Martins en el Cassanova Club.")

  @ruleAuthor(Pablo Saura)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //
agenda-group "g3"  // para inseratar a Winkel primero martins tiene que ir
no-loop true
   when
	   	crabbin : Personaje( nombre == Personaje.crabbin, ubicacion != Ubicacion.CASANOVACLUB, estadoSalud == EstadoSalud.VIVO)

	   	b : Buffer()
   then
// 

	   	modify(crabbin){
			setUbicacion(Ubicacion.CASANOVACLUB);
		};

	   	modify(b){
			append(Personaje.crabbin+" va a"+crabbin.getUbicacion().toString()+". ");
		};
 end
