package rules

import tercerhombre.personaje.Personaje;
import tercerhombre.propiedades.*;
import tercerhombre.io.Buffer;

rule "martins va cementerio" 

// **************** METADATOS ******************* //
  @ruleDate(2016-10-04)

  @ruleDescription("Martins va al cementerio al entierro de Lime. ")

  @ruleAuthor(Adrián Egea)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //

agenda-group "g1"
no-loop true
	when
		martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.CASALIME, estadoSalud == EstadoSalud.VIVO )
		
		b : Buffer()
	then

		modify(martins){
			setUbicacion(Ubicacion.CEMENTERIO);
		}
		
		modify(b){
			append(Personaje.martins+" va a"+martins.getUbicacion().toString()+". ");
		};
		
end

rule "inserta calloway"

// **************** METADATOS ******************* //
  @ruleDate(2016-11-04)

  @ruleDescription("Calloway está en el entierro, lo insertamos en la BH. ")

  @ruleAuthor(Adrián Egea)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //

no-loop true
	when
		not Personaje( nombre == Personaje.calloway)
	then
		insert(Personaje.nuevo().
    	setNombre(Personaje.calloway).
    	setGenero(Genero.HOMBRE).
    	setActividad(ActividadLegal.POLICIA).
    	setEstadoSalud(EstadoSalud.VIVO).
    	setNacionalidad(Nacionalidad.GRANBRETANA).
    	setUbicacion(Ubicacion.CEMENTERIO));
    	
end

rule "martins conoce calloway" 

// **************** METADATOS ******************* //
  @ruleDate(2016-11-04)

  @ruleDescription("Martins conoce a Calloway en el entierro de Lime. ")

  @ruleAuthor(Adrián Egea)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //

agenda-group "g1"
no-loop true
    when
        martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.CEMENTERIO, estadoSalud == EstadoSalud.VIVO  )
        calloway : Personaje( nombre == Personaje.calloway, ubicacion == Ubicacion.CEMENTERIO, estadoSalud == EstadoSalud.VIVO  )
        
        b : Buffer()
    then
        
        modify(martins){
		   getConoce_a().add(calloway);
		};
		modify(calloway){
		   getConoce_a().add(martins);
		};

        modify(b){
			append(Personaje.martins+" conoce a "+Personaje.calloway+". ").
			append(Personaje.calloway+" conoce a "+Personaje.martins+". ");
		};
		
		
		
end 

rule "van al pub" 

// **************** METADATOS ******************* //
  @ruleDate(2016-11-04)

  @ruleDescription("Martins, Calloway van al Pub a hablar sobre Lime. ")

  @ruleAuthor(Adrián Egea)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //

agenda-group "g1"
no-loop true
	when
		// calloway lleva a martins al pub, no pueden ir por separado.
		martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.CEMENTERIO, estadoSalud == EstadoSalud.VIVO  )
        calloway : Personaje( nombre == Personaje.calloway, ubicacion == Ubicacion.CEMENTERIO, estadoSalud == EstadoSalud.VIVO  )
        
        // si ambos se conocen
        Personaje( nombre == Personaje.martins ) from calloway.conoce_a
        Personaje( nombre == Personaje.calloway ) from martins.conoce_a
        
        b : Buffer()
	then
        
        modify(martins){
		   setUbicacion(Ubicacion.PUB);
		};
		modify(calloway){
		   setUbicacion(Ubicacion.PUB);
		};

        modify(b){
			append(Personaje.martins+" va a"+martins.getUbicacion().toString()+". ").
			append(Personaje.calloway+" va a"+calloway.getUbicacion().toString()+". ");
		};
		
    	
end

rule "inserta paine"

// **************** METADATOS ******************* //
  @ruleDate(2016-11-04)

  @ruleDescription("Insertamos a Paine en la BH ya que aparece en el Pub. ")

  @ruleAuthor(Adrián Egea)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //

no-loop true
	when
		not Personaje( nombre == Personaje.paine)
	then
	
    	insert(Personaje.nuevo().
    	setNombre(Personaje.paine).
    	setGenero(Genero.HOMBRE).
    	setActividad(ActividadLegal.POLICIA).
    	setEstadoSalud(EstadoSalud.VIVO).
    	setNacionalidad(Nacionalidad.GRANBRETANA).
    	setUbicacion(Ubicacion.PUB));
    	
end

rule "martins conoce a paine" 

// **************** METADATOS ******************* //
  @ruleDate(2016-11-04)

  @ruleDescription("Martins conoce a Paine puesto que van los dos al Pub junto con Calloway. ")

  @ruleAuthor(Adrián Egea)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //

agenda-group "g1"
no-loop true
	when
		martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.PUB, estadoSalud == EstadoSalud.VIVO )
		paine : Personaje( nombre == Personaje.paine, ubicacion == Ubicacion.PUB, estadoSalud == EstadoSalud.VIVO )
		calloway : Personaje( nombre == Personaje.calloway, ubicacion == Ubicacion.PUB, estadoSalud == EstadoSalud.VIVO)
		
		b : Buffer()
		
	then
		
		modify(paine){
		   getConoce_a().add(martins);
		};
		modify(paine){
		   getConoce_a().add(calloway);
		};
		modify(paine){
		   getTrabaja_con().add(calloway);
		};
		modify(calloway){
		   getConoce_a().add(paine);
		};
		modify(calloway){
		   getTrabaja_con().add(paine);
		};
		modify(martins){
		   getConoce_a().add(paine);
		};
		
		modify(b){
			append(Personaje.martins+" conoce a "+Personaje.paine+". ").
	        append(Personaje.calloway+" conoce a "+Personaje.paine+". ").
	        append(Personaje.paine+" conoce a "+Personaje.calloway+". ").
	        append(Personaje.paine+" conoce a "+Personaje.martins+". ").
	        append(Personaje.paine+" trabaja con "+Personaje.calloway+". ").
	        append(Personaje.calloway+" trabaja con "+Personaje.paine+". ");
		};
	
end

rule "martins va a hotel" 

// **************** METADATOS ******************* //
  @ruleDate(2016-11-04)

  @ruleDescription("Martins va al hotel al que se hospedará. Se inserta a Crabbin en la BH puesto que está allí. ")

  @ruleAuthor(Adrián Egea)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //

agenda-group "g1"
no-loop true
	when
		martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.PUB, estadoSalud == EstadoSalud.VIVO )
		
		b : Buffer()
	then
		
		modify(martins){
		   setUbicacion(Ubicacion.HOTELSACHER);
		};
		
		modify(b){
			append(Personaje.martins+" va a"+martins.getUbicacion().toString()+". ");
		};
		
		insert(Personaje.nuevo().
		setNombre(Personaje.crabbin).
		setGenero(Genero.HOMBRE).
		setActividad(ActividadLegal.DIRECTIVO).
		setEstadoSalud(EstadoSalud.VIVO).
		setNacionalidad(Nacionalidad.GRANBRETANA).
		setUbicacion(Ubicacion.HOTELSACHER));
		
end

rule "martins conoce crabbin" 

// **************** METADATOS ******************* //
  @ruleDate(2016-11-04)

  @ruleDescription("Martins conoce a Crabbin en el Hotel y le invita a quedarse allí. ")

  @ruleAuthor(Adrián Egea)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //

agenda-group "g1"
no-loop true
	when
		martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.HOTELSACHER, estadoSalud == EstadoSalud.VIVO )
		crabbin : Personaje( nombre == Personaje.crabbin, ubicacion == Ubicacion.HOTELSACHER, estadoSalud == EstadoSalud.VIVO )
		
		b : Buffer()
	then
		
		modify(martins){
		   getConoce_a().add(crabbin);
		};
		
		modify(crabbin){
		   getConoce_a().add(martins);
		};
		
        modify(b){
			append(Personaje.martins+" conoce a "+Personaje.crabbin+". ").
			append(Personaje.crabbin+" conoce a "+Personaje.martins+". ");
		};
		
		modify(crabbin){
		   setUbicacion(null);
		};

end

rule "insertar kurtz" 

// **************** METADATOS ******************* //
  @ruleDate(2016-11-04)

  @ruleDescription("Kurtz llama a Martins y es insertado en la B.H.")

  @ruleAuthor(Adrián Egea)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //

agenda-group "g1"
no-loop true
	when
	
		not Personaje( nombre == Personaje.kurtz)

	then
		
		insert(Personaje.nuevo().
     	setNombre(Personaje.kurtz).
     	setGenero(Genero.HOMBRE).
     	setActividad(null).
     	setEstadoSalud(EstadoSalud.VIVO).
     	setNacionalidad(Nacionalidad.AUSTRIA).
     	setUbicacion(Ubicacion.CAFEMOZART));

     	
end

rule "martins va cafe mozart" 

// **************** METADATOS ******************* //
  @ruleDate(2016-11-04)

  @ruleDescription("Kurtz y Martins deciden encontrarse en el Café Mozart para hablar de Lime.")

  @ruleAuthor(Adrián Egea)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //

agenda-group "g1"
no-loop true
	when
		martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.HOTELSACHER, estadoSalud == EstadoSalud.VIVO )
		kurtz: Personaje( nombre == Personaje.kurtz, estadoSalud == EstadoSalud.VIVO )
        
        b : Buffer()
	then
		
		modify(martins){
		   setUbicacion(Ubicacion.CAFEMOZART);
		};
		
		
		modify(b){
			append(Personaje.martins+" va a"+martins.getUbicacion().toString()+". ");
		};

end

rule "martins conoce kurtz" 

// **************** METADATOS ******************* //
  @ruleDate(2016-11-04)

  @ruleDescription("Martins y Kurtz se encuentran en el Café Mozart, se conocen.")

  @ruleAuthor(Adrián Egea)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //

agenda-group "g1"
no-loop true
	when
		martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.CAFEMOZART, estadoSalud == EstadoSalud.VIVO )
		kurtz : Personaje( nombre == Personaje.kurtz, ubicacion == Ubicacion.CAFEMOZART, estadoSalud == EstadoSalud.VIVO )
		lime : Personaje( nombre == Personaje.lime)
		
		b : Buffer()
		
	then
	
		modify(martins){
		   getConoce_a().add(kurtz);
		};
		
		modify(kurtz){
		   getConoce_a().add(martins);
		};
		
		modify(kurtz){
		   getConoce_a().add(lime);
		};
		
		modify(kurtz){
		   getAmigo_de().add(lime);
		};
		
		modify(lime){
		   getConoce_a().add(kurtz);
		};
		
		modify(lime){
		   getAmigo_de().add(kurtz);
		};
		
		modify(b){
			append(Personaje.martins+" conoce a "+Personaje.kurtz+". ").
	        append(Personaje.kurtz+" conoce a "+Personaje.martins+". ").
	        append(Personaje.kurtz+" conoce a "+Personaje.lime+". ").
	        append(Personaje.kurtz+" es amigo de "+Personaje.lime+". ").
	        append(Personaje.lime+" conoce a "+Personaje.kurtz+". ").
	        append(Personaje.lime+" es amigo de "+Personaje.kurtz+". ");
		};

end