package rules

import tercerhombre.personaje.Personaje;
import tercerhombre.propiedades.*;
import tercerhombre.io.Buffer;

/*
* -------------------------------------------------------------------
* ######################## ALTERNATIVAS ############################
* -------------------------------------------------------------------
*/




// Si calloway esta muerto, martins va al cementerio y luego vuelve a casa.
// Crear una regla general para: martins vuelve a casa.

/*
rule "calloway esta muerto y nunca conoce a martins" agenda-group "g1"
no-loop true
    when
        martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.CEMENTERIO, estadoSalud == EstadoSalud.VIVO  )
        calloway : Personaje( nombre == Personaje.calloway, estadoSalud == EstadoSalud.MUERTO  )
        
        b : Buffer()
    then

		
		
		
end 
*/


// Igual que en la regla anterior

/*
rule "kurtz esta muerto y nunca llama a martins" agenda-group "g1"
no-loop true
    when
        kurtz : Personaje( nombre == Personaje.kurtz, estadoSalud == EstadoSalud.MUERTO  )
        
        b : Buffer()
    then
		
		
end
*/
