//created on: 07-dic-2016
package rules

import tercerhombre.personaje.Personaje;
import tercerhombre.propiedades.*;
import tercerhombre.io.Buffer;


// Revisar el orden de las reglas

rule "kurtz y  martins van casa lime"

    when
    	martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.CAFEMOZART )
        kurtz : Personaje( nombre == Personaje.kurtz, ubicacion == Ubicacion.CAFEMOZART )
    then
    
    	insert(Personaje.nuevo().
    	setNombre(Personaje.anna).
    	setGenero(Genero.MUJER).
    	setActividad(ActividadLegal.ACTRIZ).
    	setEstadoSalud(EstadoSalud.VIVO).
    	setNacionalidad(null).
    	setUbicacion(null));
    
        modify(kurtz){
		setUbicacion(Ubicacion.CASALIME);
		};
		modify(martins){
		setUbicacion(Ubicacion.CASALIME);
		};
		
		

end

rule "insertar Anna"

   when
    	martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.CASALIME )
        kurtz : Personaje( nombre == Personaje.kurtz, ubicacion == Ubicacion.CASALIME )
        anna : Personaje( nombre == Personaje.anna )
        lime : Personaje( nombre == Personaje.lime )
    then
      
    	
    	modify(anna){
				setUbicacion(Ubicacion.CASALIME);
			};

		modify(anna){
	    		getConoce_a().add(lime);
	    	};
		modify(kurtz){
	    		getConoce_a().add(anna);
	    	};
		modify(lime){
	    		getConoce_a().add(anna);
	    	};
	    modify(martins){
	    		getBusca_a().add(anna);
	    }

end