//created on: 08-dic-2016
package rules

//list any import classes here.

import tercerhombre.personaje.Personaje;
import tercerhombre.propiedades.*;
import tercerhombre.io.Buffer;


rule "insertar harbin" agenda-group "g2"
no-loop true

    when

    then

    // System.out.println("insertar harbin");
    	insert(Personaje.nuevo().
    	setNombre(Personaje.harbin).
    	setGenero(Genero.HOMBRE).
    	setActividad(null).
    	setEstadoSalud(null).
    	setNacionalidad(null).
    	setUbicacion(null));
 end


rule "Winkel está en la reunion" agenda-group "g4"
no-loop true
	when
		tercerhombre : Personaje (nombre == Personaje.tercerhombre, ubicacion == Ubicacion.PUENTE )
		winkel : Personaje( nombre == Personaje.winkel, estadoSalud == EstadoSalud.VIVO, ubicacion == Ubicacion.CASAWINKEL )
		b : Buffer()
	then
// System.out.println("Winkel está en la reunion");
		modify(winkel){
			setUbicacion(Ubicacion.PUENTE);
		};
		modify(b){
			append(Personaje.winkel+" está en e"+winkel.getUbicacion().toString()+". ");
		};
end

rule "Kurtz está en la reunion" agenda-group "g4"
no-loop true
	when
		tercerhombre : Personaje (nombre == Personaje.tercerhombre, ubicacion == Ubicacion.PUENTE )
		kurtz : Personaje( nombre == Personaje.kurtz, estadoSalud == EstadoSalud.VIVO, ubicacion == Ubicacion.CASANOVACLUB )
		b : Buffer()
	then
// System.out.println("Kurtz está en la reunion");
		modify(kurtz){
			setUbicacion(Ubicacion.PUENTE);
		};
		modify(b){
			append(Personaje.kurtz+" está en e"+kurtz.getUbicacion().toString()+". ");
		};
		

end


rule "Popescu está en la reunion" agenda-group "g4"
no-loop true
	when
		tercerhombre : Personaje (nombre == Personaje.tercerhombre, ubicacion == Ubicacion.PUENTE )
		popescu : Personaje( nombre == Personaje.popescu, estadoSalud == EstadoSalud.VIVO, ubicacion == Ubicacion.CASANOVACLUB )
		b : Buffer()
	then
// System.out.println("Popescu está en la reunion");
		modify(popescu){
			setUbicacion(Ubicacion.PUENTE);
		};
		modify(b){
			append(Personaje.popescu+" está en e"+popescu.getUbicacion().toString()+". ");
		};

end




rule "Martins va a hablar con el portero" agenda-group "g4"
no-loop true
    when
		martins : Personaje ( nombre == Personaje.martins, ubicacion == Ubicacion.CASANOVACLUB )
		karl : Personaje ( nombre == Personaje.karl, estadoSalud == EstadoSalud.VIVO )
		b : Buffer()

    then
// System.out.println("Martins va a hablar con el portero");

		modify(martins){
			setUbicacion(Ubicacion.CASALIME);
		};

		modify(b){
			append(Personaje.martins+" va a"+martins.getUbicacion().toString()+". ");
		};
end

rule "Anna acompaña a Martins a ver a Karl" agenda-group "g4"
no-loop true
	when
		anna : Personaje ( nombre == Personaje.anna, ubicacion == Ubicacion.CASANOVACLUB )
		martins : Personaje ( nombre == Personaje.martins, ubicacion == Ubicacion.CASALIME )
		karl : Personaje ( nombre == Personaje.karl, estadoSalud == EstadoSalud.VIVO )
		b : Buffer()

	then
// System.out.println("Anna acompaña a Martins a ver a Karl");

    	modify(anna){
			setUbicacion(Ubicacion.CASALIME);
		};
		modify(b){
			append(Personaje.anna+" acomapaña a Martins a"+anna.getUbicacion().toString()+". ")
		};
end

rule "Karl esta muerto" agenda-group "g4"
no-loop true
	when
		karl : Personaje ( nombre == Personaje.karl, estadoSalud == EstadoSalud.VIVO )
		martins : Personaje (nombre == Personaje.martins, ubicacion == Ubicacion.CASALIME )
		b : Buffer()

	then
// System.out.println("Karl esta muerto");
		modify(karl){
			setEstadoSalud(EstadoSalud.MUERTO);
		};

		modify(karl){
			setUbicacion(Ubicacion.CEMENTERIO);
		};
		modify(b) {
			append(Personaje.karl+" está "+karl.getEstadoSalud().toString()+". ");
		};
end

rule "Martins va a dar la conferencia" agenda-group "g4"
no-loop true
    when
		martins : Personaje (nombre == Personaje.martins, ubicacion == Ubicacion.CASALIME )
		karl : Personaje (nombre == Personaje.karl, estadoSalud == EstadoSalud.MUERTO )
		crabbin : Personaje (nombre == Personaje.crabbin, estadoSalud == EstadoSalud.VIVO)

		b : Buffer()

    then
// System.out.println("Martins va a dar la conferencia");
    	modify(crabbin){
			setUbicacion(Ubicacion.CONFERENCIA);
		};
		modify(martins){
			setUbicacion(Ubicacion.CONFERENCIA);
		};

		modify(b){
			append(Personaje.martins+" va a"+martins.getUbicacion().toString()+". ").
			append(Personaje.crabbin+" va a"+karl.getEstadoSalud().toString()+". ");
		};
end

rule "Popescu intenta matar a Martin" agenda-group "g4"
no-loop true
    when
		martins : Personaje (nombre == Personaje.martins, ubicacion == Ubicacion.CONFERENCIA )
		crabbin : Personaje (nombre == Personaje.crabbin, ubicacion == Ubicacion.CONFERENCIA )
		popescu : Personaje (nombre == Personaje.popescu , estadoSalud == EstadoSalud.VIVO )

		b : Buffer()

    then
// System.out.println("Popescu intenta matar a Martin");

    	modify(popescu){
			setUbicacion(Ubicacion.CONFERENCIA);
		};
		modify(crabbin){
    		getConoce_a().add(popescu);
    	};

		modify(popescu){
    		getConoce_a().add(crabbin);
    	};

		modify(popescu){
    		getEnfrentado_con().add(martins);
    	};

		modify(martins){
    		getEnfrentado_con().add(popescu);
    	};

		modify(b){
			append(Personaje.popescu+" va a"+popescu.getUbicacion().toString()+". ").
			append(Personaje.crabbin+" conoce a "+Personaje.popescu+". ").
			append(Personaje.popescu+" conoce a "+Personaje.crabbin+". ").
			append(Personaje.popescu+" enfrentado con "+Personaje.martins+". ").
			append(Personaje.martins+" enfrentado con "+Personaje.popescu+". ").
			append(Personaje.popescu+" intenta matar a "+Personaje.martins+". ");
		};
end



rule "Calloway le cuenta la verdad a martins" agenda-group "g4"
no-loop true
    when
		martins : Personaje (nombre == Personaje.martins, ubicacion == Ubicacion.CONFERENCIA )
		kurtz : Personaje (nombre == Personaje.kurtz )
		calloway : Personaje (nombre == Personaje.calloway)
		harbin : Personaje (nombre == Personaje.harbin )
		lime : Personaje (nombre == Personaje.lime )

		b : Buffer()

    then
// System.out.println("Calloway le cuenta la verdad a martins");

    	modify(calloway){
			setUbicacion(Ubicacion.COMISARIA);
		};

    	modify(martins){
			setUbicacion(Ubicacion.COMISARIA);
		};

		modify(b){
			append(Personaje.calloway+" va a"+calloway.getUbicacion().toString()+". ").
			append(Personaje.martins+" va a"+martins.getUbicacion().toString()+". ").
			append(Personaje.calloway+" le muestra la verdad a Martins");
		};

		modify(martins){
			getEnfrentado_con().remove(calloway);
		};

		modify(b){
			append(Personaje.martins+" ya no está enfrentado con "+Personaje.calloway+". ");
		};

		modify(kurtz){
    		getTrabaja_con().add(lime);
    	};

		modify(lime){
    		getTrabaja_con().add(kurtz);
    	};

    	modify(lime){
    		getTrabaja_con().add(harbin);
    	};

    	modify(harbin){
    		getTrabaja_con().add(lime);
    	};

    	modify(kurtz){
			getTrabaja_con().add(harbin);
		};

		modify(harbin){
    		getTrabaja_con().add(kurtz);
    	};
    	// METER CONSULTAS CONOCER


    	modify(lime){
    		setActividad(ActividadIlegal.TRAFICANTE);
    	};

    	modify(kurtz){
    		setActividad(ActividadIlegal.TRAFICANTE);
    	};

    	modify(harbin){
    		setActividad(ActividadIlegal.TRAFICANTE);
    	};

    	modify(b){
			append("Se descubre que Lime, Kurtz y Harbin trabajan juntos siendo traficantes de penicilina. ");
		};

end

rule "Martins decide irse e informa a Anna" agenda-group "g4"
no-loop true
    when
		martins : Personaje (nombre == Personaje.martins )
		anna : Personaje (nombre == Personaje.anna, estadoSalud == EstadoSalud.VIVO )
		harbin : Personaje (nombre == Personaje.harbin, actividad == ActividadIlegal.TRAFICANTE )

		b : Buffer()

    then
// System.out.println("Martins decide irse e informa a Anna");
    	modify(martins){
			setUbicacion(Ubicacion.CASAANNA);
		};
		modify(anna){
			setUbicacion(Ubicacion.CASAANNA);
		};
		modify(martins){
    		getQuiere_a().add(anna);
    	};

		modify(b){
			append(Personaje.martins+" va a"+martins.getUbicacion().toString()+". ").
			append(Personaje.anna+" va a"+anna.getUbicacion().toString()+". ").
			append(Personaje.martins+" le dice a Anna que ha decidido irse a Estados Unidos.").
			append(Personaje.martins+" quiere a "+Personaje.anna);
		};
end

rule "Paine esta en la comisaria" agenda-group "g4"
no-loop true
	when
		paine : Personaje (nombre == Personaje.paine, ubicacion == Ubicacion.COMISARIA, estadoSalud == EstadoSalud.VIVO)
		calloway : Personaje (nombre == Personaje.calloway, ubicacion == Ubicacion.COMISARIA)
		martins : Personaje (nombre == Personaje.martins, ubicacion == Ubicacion.COMISARIA)
		b : Buffer()
	then
// System.out.println("Paine esta en la comisaria");
		modify(paine){
			setUbicacion(Ubicacion.COMISARIA);
		};

		modify(martins){
			getEnfrentado_con().remove(paine);
		};

		modify(b){
			append(Personaje.paine+" va a"+paine.getUbicacion().toString()+". ").
			append(Personaje.martins+" ya no está enfrentado con "+Personaje.paine+". ");
		};

end


