//created on: 11-dic-2016
package rules

import tercerhombre.personaje.Personaje;
import tercerhombre.propiedades.*;
import tercerhombre.io.Buffer;

rule "problemas en casa de anna" agenda-group "g3"
no-loop true
	when
    	martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.CASAANNA )
        anna : Personaje( nombre == Personaje.anna, ubicacion == Ubicacion.CASAANNA )
        paine : Personaje( nombre == Personaje.paine )
        calloway : Personaje( nombre == Personaje.calloway )

        b : Buffer()

    then
    	 modify(calloway){
	    	setUbicacion(Ubicacion.CASAANNA);
	    };
	    modify(paine){
	    	setUbicacion(Ubicacion.CASAANNA);
	    };
      modify(anna){
	    	getConoce_a().add(calloway)
	    };
	    modify(anna){
	    	getConoce_a().add(paine)
	    };
	    modify(calloway){
	    	getConoce_a().add(anna)
	    };
	    modify(paine){
	    	getConoce_a().add(anna)
	    };
	    modify(martins){
    		getEnfrentado_con().add(calloway);
    	};
		modify(martins){
    		getEnfrentado_con().add(paine);
    	};

    	modify(b){
			append("Martins va a"+martins.getUbicacion().toString()+". ").
			append("Paine va a"+paine.getUbicacion().toString()+". ").
			append("Anna conoce a "+Personaje.calloway+". ").
			append("Anna conoce a "+Personaje.paine+". ").
			append("Calloway conoce a "+Personaje.anna+". ").
			append("Paine conoce a "+Personaje.anna+". ").
			append("Martins enfrentado con "+Personaje.calloway+". ").
			append("Martins enfrentado con "+Personaje.paine+". ");
		};

end

 rule "van a la comisaria " agenda-group "g3"
 no-loop true
	when
    	martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.CASAANNA )
        anna : Personaje( nombre == Personaje.anna, ubicacion == Ubicacion.CASAANNA )
        paine : Personaje( nombre == Personaje.paine, ubicacion == Ubicacion.CASAANNA )
        calloway : Personaje( nombre == Personaje.calloway, ubicacion == Ubicacion.CASAANNA )

				b : Buffer()

    then
    	modify(calloway){
	    	setUbicacion(Ubicacion.COMISARIA);
	    };
	    modify(paine){
	    	setUbicacion(Ubicacion.COMISARIA);
	    };
	    modify(anna){
	    	setUbicacion(Ubicacion.COMISARIA);
	    };

			modify(b){
			append("Calloway va a"+calloway.getUbicacion().toString()+". ").
			append("Paine va a"+paine.getUbicacion().toString()+". ").
			append("Anna va a"+anna.getUbicacion().toString()+". ");
		};
end

rule "va a ver a winkel" agenda-group "g3"
no-loop true
	when
    	martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.CASAANNA )
        winkel : Personaje( nombre == Personaje.winkel )

				b : Buffer()

    then

      	modify(winkel){
			setUbicacion(Ubicacion.CASAWINKEL);
		};
		modify(martins){
			setUbicacion(Ubicacion.CASAWINKEL);
		};

		modify(b){
		append("Winkel va a"+winkel.getUbicacion().toString()+". ").
		append("Martins va a"+martins.getUbicacion().toString()+". ");
	};

    end

rule "visita a Winkel" agenda-group "g3"  // para inseratar a Winkel primero martins tiene que ir
no-loop true
   when
    	martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.CASAWINKEL )
        winkel : Personaje( nombre == Personaje.winkel, ubicacion == Ubicacion.CASAWINKEL )

				b : Buffer()

    then
    	modify(martins){
      		getConoce_a().add(winkel);
      	};

      	modify(winkel){
      		getConoce_a().add(martins);
      	};

				modify(b){
				append("Martins conoce a "+Personaje.winkel+". ").
				append("Winkel conoce a "+Personaje.martins+". ");
			};
end

rule "martins y anna van al cassanovaclub" agenda-group "g3"  // para inseratar a Winkel primero martins tiene que ir
no-loop true
   when
    	martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.COMISARIA )
        anna : Personaje( nombre == Personaje.winkel, ubicacion == Ubicacion.COMISARIA )
        kurtz : Personaje( nombre == Personaje.kurtz )
        popescu : Personaje( nombre == Personaje.popescu )
        tercerhombre : Personaje( nombre == Personaje.tercerhombre )

				b : Buffer()

    then
    	modify(anna){
    		getConoce_a().add(kurtz);
    	};

		modify(anna){
    		getConoce_a().add(popescu);
    	};

    	modify(anna){
			setUbicacion(Ubicacion.CASANOVACLUB);
		};

		modify(kurtz){
			setUbicacion(Ubicacion.CASANOVACLUB);
		};

		modify(popescu){
			setUbicacion(Ubicacion.CASANOVACLUB);
		};

		modify(martins){
			setUbicacion(Ubicacion.CASANOVACLUB);
		};

		modify(popescu){
    		getSospecha_de().add(martins);
    	};

    	modify(martins){
    		getConoce_a().add(popescu);
    	};

		modify(popescu){
    		getConoce_a().add(martins);
    	};

    	modify(martins){
    		getBusca_a().add(tercerhombre);
    	};

			modify(b){
			append("Anna conoce a "+Personaje.kurtz+". ").
			append("Anna conoce a "+Personaje.popescu+". ").
			append("Popescu conoce a "+Personaje.anna+". ").
			append("Martins conoce a "+Personaje.popescu+". ").
			append("Popescu conoce a "+Personaje.martins+". ").
			append("Anna va a"+anna.getUbicacion().toString()+". ").
			append("Kurtz va a"+kurtz.getUbicacion().toString()+". ").
			append("Popescu va a"+popescu.getUbicacion().toString()+". ").
			append("Martins va a"+martins.getUbicacion().toString()+". ").
			append("Popescu sospecha de "+Personaje.martins+". ").
			append("Martins busca a "+Personaje.tercerhombre+". ");
		};
end
