//created on: 08-dic-2016
package rules

//list any import classes here.

import tercerhombre.personaje.Personaje;
import tercerhombre.propiedades.*;
import tercerhombre.io.Buffer;
import tercerhombre.Fin;


rule "Anna esta en el final" 

// **************** METADATOS ******************* //
  @ruleDate(2016-12-06)

  @ruleDescription("Anna está en el cementerio cuando están enterrando a Lime.")

  @ruleAuthor(Jesús Garcerán)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //

	agenda-group "g5"
	no-loop true
	when
		anna : Personaje (nombre == Personaje.anna, ubicacion == Ubicacion.CAFEMARC, estadoSalud == EstadoSalud.VIVO )
		martins : Personaje (nombre == Personaje.martins, ubicacion == Ubicacion.CEMENTERIO )
		calloway : Personaje (nombre == Personaje.calloway, ubicacion == Ubicacion.CEMENTERIO )
		lime : Personaje (nombre == Personaje.lime, estadoSalud == EstadoSalud.MUERTO )
		b : Buffer()

	then
		
		modify(anna){
			setUbicacion(Ubicacion.CEMENTERIO);
		}
		modify(b){
			append(Personaje.anna+"está en e"+anna.getUbicacion().toString()+". ").
			append(Personaje.anna+" ignora a Martins.");
		};
end

rule "Paine esta en el final" 

// **************** METADATOS ******************* //
  @ruleDate(2016-12-06)

  @ruleDescription("Paine está en el cementerio cuando están enterrando a Lime. ")

  @ruleAuthor(Jesús Garcerán)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //

	agenda-group "g5"
	no-loop true
	when
		paine : Personaje (nombre == Personaje.paine, estadoSalud == EstadoSalud.VIVO )
		martins : Personaje (nombre == Personaje.martins, ubicacion == Ubicacion.CEMENTERIO )
		lime : Personaje (nombre == Personaje.lime, estadoSalud == EstadoSalud.MUERTO )
		b : Buffer()

	then

		modify(paine){
			setUbicacion(Ubicacion.CEMENTERIO);
		}
		modify(b){
			append(Personaje.paine +" está en e"+paine.getUbicacion().toString()+". ");
		};
end


rule "Lime hace acto de presencia" 

// **************** METADATOS ******************* //
  @ruleDate(2016-12-06)

  @ruleDescription("Lime hace acto de presencia a Martins cerca de casa de Anna.")

  @ruleAuthor(Jesús Garcerán)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //

agenda-group "g5"
no-loop true
	when
		lime : Personaje ( nombre == Personaje.lime, estadoSalud == EstadoSalud.MUERTO, ubicacion != Ubicacion.CLOACAS )
		martins : Personaje ( nombre == Personaje.martins, ubicacion != Ubicacion.CEMENTERIO )
		not Personaje( nombre == Personaje.calloway ) from martins.enfrentado_con

		b : Buffer()
	then
 

		modify(lime){
			setEstadoSalud(EstadoSalud.VIVO);
		}
		modify(b){
			append(Personaje.lime+" le aparece a Martins en la calle. ");
		};
		modify(lime){
			setUbicacion(Ubicacion.PLAZA);
		}
		modify(martins){
			setUbicacion(Ubicacion.PLAZA);
		}
		modify(b){
			append(Personaje.lime+" y Martins llegan a"+lime.getUbicacion().toString());
		};
		modify(lime){
			setUbicacion(Ubicacion.CLOACAS);
		};
		modify(b){
			append(Personaje.lime+" desaparece, se esconde y va a"+lime.getUbicacion().toString()+". ");
		};


end

rule "Calloway va a la Plaza" 

// **************** METADATOS ******************* //
  @ruleDate(2016-12-06)

  @ruleDescription("Calloway va a la plaza en la que Lime desapareció.")

  @ruleAuthor(Jesús Garcerán)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //

agenda-group "g5"
no-loop true
	when
		calloway : Personaje (nombre == Personaje.calloway, ubicacion == Ubicacion.COMISARIA )
		harbin : Personaje ( nombre == Personaje.harbin,ubicacion != Ubicacion.CEMENTERIO )

		b : Buffer()
	then

		modify(calloway){
			setUbicacion(Ubicacion.PLAZA);
		}
		modify(b){
			append(Personaje.calloway+" va a"+calloway.getUbicacion().toString());
		};

end

rule "Paine va a la Plaza" 

// **************** METADATOS ******************* //
  @ruleDate(2016-12-06)

  @ruleDescription("Paine va a la plaza en la que Lime desapareció.")

  @ruleAuthor(Jesús Garcerán)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //

agenda-group "g5"
no-loop true
	when
		martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.PLAZA )
		paine : Personaje (nombre == Personaje.paine, ubicacion == Ubicacion.COMISARIA )
		harbin : Personaje ( nombre == Personaje.harbin,ubicacion != Ubicacion.CEMENTERIO)
		b : Buffer()
	then

		modify(paine){
			setUbicacion(Ubicacion.PLAZA);
		}
		modify(b){
			append(Personaje.paine+" va a"+paine.getUbicacion().toString());
		};

end

rule "Calloway y Martins buscan a Lime en las cloacas" 

// **************** METADATOS ******************* //
  @ruleDate(2016-12-06)

  @ruleDescription("Calloway y Martins buscan a Lime en las cloacas tras descubrir que se fue por allí.")

  @ruleAuthor(Jesús Garcerán)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //

agenda-group "g5"
	no-loop true
	when
		martins : Personaje ( nombre == Personaje.martins, ubicacion == Ubicacion.PLAZA )
		calloway : Personaje (nombre == Personaje.calloway, ubicacion == Ubicacion.PLAZA )
		harbin : Personaje ( nombre == Personaje.harbin,ubicacion != Ubicacion.CEMENTERIO )

		b : Buffer()
	then

		modify(calloway){
			setUbicacion(Ubicacion.CLOACAS);
		}

		modify(martins){
			setUbicacion(Ubicacion.CLOACAS);
		}

		modify(b){
			append(Personaje.martins+" y Calloway buscan a Lime en"+calloway.getUbicacion().toString()+". ");
		};
end

rule "Paine esta con calloway en las cloacas" 

// **************** METADATOS ******************* //
  @ruleDate(2016-12-06)

  @ruleDescription("Paine va con Calloway y Martins a las cloacas en busca de Lime.")

  @ruleAuthor(Jesús Garcerán)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //

agenda-group "g5"
	no-loop true
	when
		martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.CLOACAS )
		calloway : Personaje (nombre == Personaje.calloway, ubicacion == Ubicacion.CLOACAS )
		harbin : Personaje ( nombre == Personaje.harbin,ubicacion != Ubicacion.CEMENTERIO)
		paine : Personaje (nombre == Personaje.paine, ubicacion == Ubicacion.PLAZA,
							estadoSalud == EstadoSalud.VIVO )
		b : Buffer()

	then

		modify(paine){
			setUbicacion(Ubicacion.CLOACAS);
		}

		modify(b){
			append(Personaje.paine+" está con Martins y Calloway y buscan a Lime en"+paine.getUbicacion().toString()+". ");
		};

end

rule "Harbin esta enterrado en la tumba de Lime" 

// **************** METADATOS ******************* //
  @ruleDate(2016-12-06)

  @ruleDescription("Al abrir la tumba de Lime, Martins y Calloway encuentran a Harbin enterrado ahí.")

  @ruleAuthor(Jesús Garcerán)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //

agenda-group "g5"
    no-loop true
    when
		martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.CLOACAS )
		calloway : Personaje (nombre == Personaje.calloway, ubicacion == Ubicacion.CLOACAS )
		harbin : Personaje (nombre == Personaje.harbin, ubicacion != Ubicacion.CEMENTERIO, estadoSalud != EstadoSalud.VIVO)

		b : Buffer()
    then

        modify(calloway){
			setUbicacion(Ubicacion.CEMENTERIO);
		}
		modify(martins){
			setUbicacion(Ubicacion.CEMENTERIO);
		}

		modify(b){
			append(Personaje.calloway+" y Martins van a"+calloway.getUbicacion().toString());
		};

		modify(harbin){
			setUbicacion(Ubicacion.CEMENTERIO);
		}

		modify(harbin){
			setEstadoSalud(EstadoSalud.MUERTO);
		}

		modify(b){
			append("Encuentran el cadáver de Harbin en la tumba de Lime");
		};
end

rule "Paine esta en el cementerio también" 
// **************** METADATOS ******************* //
  @ruleDate(2016-12-06)

  @ruleDescription("Paine acompaña a Calloway y Martins en el cementerio abriendo la tumba de Lime.")

  @ruleAuthor(Jesús Garcerán)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //

agenda-group "g5"
	no-loop true
    when
    	martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.CEMENTERIO )
		calloway : Personaje (nombre == Personaje.calloway, ubicacion == Ubicacion.CEMENTERIO )
    	paine : Personaje (nombre == Personaje.paine, ubicacion == Ubicacion.CLOACAS )
    	lime : Personaje (nombre == Personaje.lime, estadoSalud == EstadoSalud.VIVO )
    	b : Buffer()

    then
    
    	
		modify(paine){
			setUbicacion(Ubicacion.CEMENTERIO);
		}
		modify(b){
			append("Paine va a"+paine.getUbicacion().toString()+" con Calloway y Martins");
		};

end

rule "Llevan a Anna a la comisaria" 

// **************** METADATOS ******************* //
  @ruleDate(2016-12-06)

  @ruleDescription("Van a casa de Anna y la llevan a comisaria por el pasaporte falso.")

  @ruleAuthor(Jesús Garcerán)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //

agenda-group "g5"
    no-loop true
    when
		martins : Personaje (nombre == Personaje.martins, ubicacion == Ubicacion.CEMENTERIO )
		anna : Personaje (nombre == Personaje.anna, nacionalidad != Nacionalidad.AUSTRIA, ubicacion != Ubicacion.CEMENTERIO, estadoSalud == EstadoSalud.VIVO )
		lime : Personaje (nombre == Personaje.lime, estadoSalud == EstadoSalud.VIVO )
		calloway : Personaje (nombre == Personaje.calloway, ubicacion == Ubicacion.CEMENTERIO )
		harbin : Personaje (nombre == Personaje.harbin, estadoSalud != null )

		b : Buffer()
    then

        modify(anna){
			setUbicacion(Ubicacion.COMISARIA);
		}
		modify(martins){
			setUbicacion(Ubicacion.COMISARIA);
		}
		modify(calloway){
			setUbicacion(Ubicacion.COMISARIA);
		}
		modify(anna){
   		getBusca_a().add(lime);
		};

		modify(b){
			append("Llevan a Anna a"+anna.getUbicacion().toString()+" por su pasaporte falso. ").
			append(Personaje.martins+" le dice a Anna que ha visto a Lime. ").
			append(Personaje.calloway+" le pide ayuda a Anna para encontrar a Lime y ella lo rechaza. ").
			append(Personaje.anna+" busca a Lime. ");
		};

end

rule "Martins va al Sector Ruso a hablar con Lime" 

// **************** METADATOS ******************* //
  @ruleDate(2016-12-06)

  @ruleDescription("Martins va en busca de Lime y va a una casa en el Sector Ruso.")

  @ruleAuthor(Jesús Garcerán)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //

agenda-group "g5"
    no-loop true
    when
		martins : Personaje (nombre == Personaje.martins, ubicacion == Ubicacion.COMISARIA || ubicacion == Ubicacion.CEMENTERIO )
		lime : Personaje (nombre == Personaje.lime, ubicacion == Ubicacion.CLOACAS)
		tercerhombre : Personaje (nombre == Personaje.tercerhombre)

		b : Buffer()
	then


        modify(martins){
			setUbicacion(Ubicacion.SECTORRUSO);
		}
		modify(lime){
			setUbicacion(Ubicacion.SECTORRUSO);
		}

		modify(b){
			append(Personaje.martins+" va a"+martins.getUbicacion().toString()+" para buscar a Lime. ");
		};

		modify(martins){
			setUbicacion(Ubicacion.NORIA);
		}
		modify(lime){
			setUbicacion(Ubicacion.NORIA);
		}

		modify(b){
			append(Personaje.martins+" y Lime hablan en "+martins.getUbicacion().toString()+". ");
		};

		modify(tercerhombre) {
			getEn_realidad_es().add(lime);
		}
		
		modify(lime){
			getEn_realidad_es().add(tercerhombre);
		}

		modify(b){
			append("En la conversación se confirma que el tercer hombre es "+tercerhombre.getNombre()+". ");
		};

end

rule "Kurtz esta con Lime" 

// **************** METADATOS ******************* //
  @ruleDate(2016-12-06)

  @ruleDescription("En la casa del Sector Ruso, Kurtz está en la casa con Lime.")

  @ruleAuthor(Jesús Garcerán)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //

agenda-group "g5"
    no-loop true
    when
    	lime : Personaje (nombre == Personaje.lime, ubicacion == Ubicacion.NORIA)
		tercerhombre : Personaje (nombre == Personaje.tercerhombre)
		kurtz : Personaje (nombre == Personaje.kurtz, ubicacion != Ubicacion.SECTORRUSO)
		b : Buffer()
    then

    	modify(kurtz){
			setUbicacion(Ubicacion.SECTORRUSO);
		}
		modify(b){
			append(Personaje.kurtz+" está en e"+kurtz.getUbicacion().toString()+" junto con Lime. ");
		};

end

rule "Winkel esta con Lime" 

// **************** METADATOS ******************* //
  @ruleDate(2016-12-06)

  @ruleDescription("En la casa del Sector Ruso, Winkel está en la casa con Lime.")

  @ruleAuthor(Jesús Garcerán)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //


agenda-group "g5"
    no-loop true
    when
    	lime : Personaje (nombre == Personaje.lime, ubicacion == Ubicacion.NORIA)
		tercerhombre : Personaje (nombre == Personaje.tercerhombre)
		winkel : Personaje (nombre == Personaje.winkel, ubicacion != Ubicacion.SECTORRUSO)
		b : Buffer()
    then

    	modify(winkel){
			setUbicacion(Ubicacion.SECTORRUSO);
		}

		modify(b){
			append(Personaje.winkel+" está en e"+winkel.getUbicacion().toString()+" junto con Lime. ");
		};
end

rule "Martins decide ayudar a Calloway" 

// **************** METADATOS ******************* //
  @ruleDate(2016-12-06)

  @ruleDescription("Tras hablar con Lime, Martins decide ayudar a Calloway y va a la comisaria.")

  @ruleAuthor(Jesús Garcerán)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //


agenda-group "g5"
    no-loop true
    when
		martins : Personaje (nombre == Personaje.martins, ubicacion == Ubicacion.NORIA )
		calloway : Personaje (nombre == Personaje.calloway )
		paine : Personaje (nombre == Personaje.paine )

		b : Buffer()
    then

        modify(martins){
			setUbicacion(Ubicacion.COMISARIA);
		}
		modify(calloway){
			setUbicacion(Ubicacion.COMISARIA);
		}


		modify(b){
			append(Personaje.martins+", Calloway se reunen en "+martins.getUbicacion().toString()+". ");
		};
		
		//modify(b){
			//append(Personaje.martins+" cede a ayudar a Calloway a atrapar a Lime si él lleva a Anna de vuelta a Rusia. ");
		//};
end


rule "Paine esta con ellos" 

// **************** METADATOS ******************* //
  @ruleDate(2016-12-06)

  @ruleDescription("En la comisaria, cuando se reunen Martins y Calloway, también está Paine.")

  @ruleAuthor(Jesús Garcerán)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //


agenda-group "g5"
no-loop true
    when
		martins : Personaje (nombre == Personaje.martins, ubicacion == Ubicacion.COMISARIA )
		calloway : Personaje (nombre == Personaje.calloway, ubicacion == Ubicacion.COMISARIA )
		lime : Personaje (nombre == Personaje.lime, ubicacion == Ubicacion.NORIA )
		paine : Personaje (nombre == Personaje.paine, ubicacion != Ubicacion.COMISARIA, estadoSalud == EstadoSalud.VIVO )

		b : Buffer()
    then

		modify(paine){
			setUbicacion(Ubicacion.COMISARIA);
		}
		modify(b){
			append(Personaje.paine+" acompaña a Martins y Calloway en"+paine.getUbicacion().toString()+". ");
		};

end


rule "Martins y Anna discuten en la estacion" 

// **************** METADATOS ******************* //
  @ruleDate(2016-12-06)

  @ruleDescription("Martins va a ver como Anna coge el tren y Anna lo ve y discuten.")

  @ruleAuthor(Jesús Garcerán)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //


agenda-group "g5"
    no-loop true
    when
		martins : Personaje (nombre == Personaje.martins, ubicacion == Ubicacion.COMISARIA )
		anna : Personaje (nombre == Personaje.anna, estadoSalud == EstadoSalud.VIVO )
		lime : Personaje (nombre == Personaje.lime, ubicacion == Ubicacion.NORIA )


		b : Buffer()
    then

        modify(martins){
			setUbicacion(Ubicacion.ESTACION);
		}
		modify(anna){
			setUbicacion(Ubicacion.ESTACION);
		}

		modify(anna){
    		getEnfrentado_con().add(martins);
    	};

		modify(anna){
			getAmigo_de().remove(martins);
		};

		modify(b){
			append(Personaje.martins+" espera en "+martins.getUbicacion().toString()+" a que Anna coja el tren. ").
			append(Personaje.anna+" llega a"+anna.getUbicacion().toString()+" y ve a Martins .").
			append(Personaje.anna+" y Martins discuten y Anna decide no coger el tren. ").
			append(Personaje.anna+" está enfrentada con Martins. ");

		};
end

// SUCEDE POR QUE ANNA LE HACE DUDAR
rule "Martins y Calloway van al hospital" 

// **************** METADATOS ******************* //
  @ruleDate(2016-12-06)

  @ruleDescription("Martins duda si ayudar a Calloway, y para convencerlo, Calloway lo lleva al hospital.")

  @ruleAuthor(Jesús Garcerán)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //


agenda-group "g5"
	no-loop true
	when
		martins : Personaje (nombre == Personaje.martins, ubicacion == Ubicacion.ESTACION )
		calloway : Personaje (nombre == Personaje.calloway )

		b : Buffer()

    then

        modify(martins){
			setUbicacion(Ubicacion.COMISARIA);
		}
		modify(calloway){
			setUbicacion(Ubicacion.COMISARIA);
		}

		modify(b){
			append(Personaje.martins+" habla con Calloway en"+martins.getUbicacion().toString()+" y duda.");
		};

		modify(martins){
			setUbicacion(Ubicacion.HOSPITAL);
		}
		modify(calloway){
			setUbicacion(Ubicacion.HOSPITAL);
		}

		modify(b){
			append(Personaje.calloway+" lleva a Martins a"+martins.getUbicacion().toString()+" y convence a Martins para que le ayude.");
		};
end

rule "Martins y Lime se ven en el cafe" 

// **************** METADATOS ******************* //
  @ruleDate(2016-12-06)

  @ruleDescription("Martins decide quedar con Lime en el Cafe Marc y Calloway espera fuera.")

  @ruleAuthor(Jesús Garcerán)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //


agenda-group "g5"
	no-loop true
	when
		martins : Personaje (nombre == Personaje.martins, ubicacion == Ubicacion.HOSPITAL )
		calloway : Personaje (nombre == Personaje.calloway )
		lime : Personaje (nombre == Personaje.lime )

		b : Buffer()

    then

        modify(martins){
			setUbicacion(Ubicacion.CAFEMARC);
		}
		modify(calloway){
			setUbicacion(Ubicacion.CAFEMARC);
		}
		
		modify(lime){
			setUbicacion(Ubicacion.CAFEMARC);
		}
		modify(b) {
			append(Personaje.lime+" aparece en e"+lime.getUbicacion().toString()+". ");
		};

		modify(b){
			append(Personaje.martins+" queda con Lime en e"+martins.getUbicacion().toString()+". ").
			append(Personaje.calloway+" esta fuera esperando la llegada de Lime. ");
		};

end





rule "Paine esta en el Café Marc" 

// **************** METADATOS ******************* //
  @ruleDate(2016-12-06)

  @ruleDescription("Paine también esta fuera del Café Marc con Calloway esperando a Lime.")

  @ruleAuthor(Jesús Garcerán)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //

agenda-group "g5"
	no-loop true
	when
		paine : Personaje (nombre == Personaje.paine, ubicacion != Ubicacion.CAFEMARC )
		martins : Personaje (nombre == Personaje.martins, ubicacion == Ubicacion.CAFEMARC )
		calloway : Personaje (nombre == Personaje.calloway, ubicacion == Ubicacion.CAFEMARC )
		b : Buffer()

	then

		modify(paine){
			setUbicacion(Ubicacion.CAFEMARC);
		}
		modify(b) {
			append(Personaje.paine+" está con Calloway fuera de e"+paine.getUbicacion().toString()+" esperando a Lime. ");
		};
end


rule "Anna va al Café Marc" 

// **************** METADATOS ******************* //
  @ruleDate(2016-12-06)

  @ruleDescription("Anna aparece en el Café Marc y le dice a Lime que huya.")

  @ruleAuthor(Jesús Garcerán)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //


agenda-group "g5"
	no-loop true
	when
		anna : Personaje (nombre == Personaje.anna, ubicacion != Ubicacion.CAFEMARC && ubicacion != Ubicacion.CEMENTERIO, estadoSalud == EstadoSalud.VIVO )
		lime : Personaje (nombre == Personaje.lime, ubicacion == Ubicacion.CAFEMARC, estadoSalud == EstadoSalud.VIVO )
		b : Buffer()

	then

		modify(anna){
			setUbicacion(Ubicacion.CAFEMARC);
		}
		modify(b) {
			append(Personaje.anna+" está en e"+anna.getUbicacion().toString()+". ").
			append(Personaje.anna+" le dice a Lime que huya. ");
		};
end


rule "Desenlace en las cloacas" 

// **************** METADATOS ******************* //
  @ruleDate(2016-12-06)

  @ruleDescription("Lime huye por las cloacas y Martins y Calloway lo siguen.")

  @ruleAuthor(Jesús Garcerán)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //


agenda-group "g5"
	no-loop true
	when
		martins : Personaje (nombre == Personaje.martins, ubicacion == Ubicacion.CAFEMARC )
		calloway : Personaje (nombre == Personaje.calloway )
		lime : Personaje (nombre == Personaje.lime )

		b : Buffer()
    then

        modify(martins){
			setUbicacion(Ubicacion.CLOACAS);
		}
		modify(calloway){
			setUbicacion(Ubicacion.CLOACAS);
		}

		modify(lime){
			setUbicacion(Ubicacion.CLOACAS);
		}

		modify(b){
			append(Personaje.lime+" huye a"+lime.getUbicacion().toString()+"y Martins y Calloway le persiguen. ");
		};
end

rule "Paine está en las cloacas" 

// **************** METADATOS ******************* //
  @ruleDate(2016-12-06)

  @ruleDescription("Paine está con Calloway cuando van a las cloacas a por Lime.")

  @ruleAuthor(Jesús Garcerán)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //


agenda-group "g5"
	no-loop true
	when
		martins : Personaje (nombre == Personaje.martins, ubicacion == Ubicacion.CLOACAS )
		calloway : Personaje (nombre == Personaje.calloway, ubicacion == Ubicacion.CLOACAS )
		lime : Personaje (nombre == Personaje.lime, ubicacion == Ubicacion.CLOACAS )
		paine : Personaje (nombre == Personaje.paine, ubicacion != Ubicacion.CLOACAS, estadoSalud == EstadoSalud.VIVO )

		b : Buffer()

	then


		modify(paine){
			setUbicacion(Ubicacion.CLOACAS);
		}
		modify(b) {
			append("Paine está con Calloway y Martins en las Cloacas buscando a Lime. ");
		};

end

rule "Muere Lime" 

// **************** METADATOS ******************* //
  @ruleDate(2016-12-06)

  @ruleDescription("Finalmente Martins dispará a Lime por que Lime se lo pide.")

  @ruleAuthor(Jesús Garcerán)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //


agenda-group "g5"
	no-loop true
	when
		martins : Personaje (nombre == Personaje.martins, ubicacion == Ubicacion.CLOACAS )
		lime : Personaje (nombre == Personaje.lime, ubicacion == Ubicacion.CLOACAS )
		b : Buffer()

	then

		modify(b) {
			append("Calloway y Martins encuentran a Lime y Martins mata a Lime. ");
		};

		modify(lime){
			setEstadoSalud(EstadoSalud.MUERTO);
		}
		
		modify(martins){
			getMata_a().add(lime);
		}
		
		modify(lime){
			getMata_a().add(martins);
		}
		
end




rule "Final" 
// **************** METADATOS ******************* //
  @ruleDate(2016-12-06)

  @ruleDescription("En el entierro de Lime van Martins y Calloway.")

  @ruleAuthor(Jesús Garcerán)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //


agenda-group "g5"
	no-loop true
	when
		martins : Personaje (nombre == Personaje.martins, ubicacion == Ubicacion.CLOACAS )
		calloway : Personaje (nombre == Personaje.calloway )
		lime : Personaje (nombre == Personaje.lime, ubicacion == Ubicacion.CLOACAS, estadoSalud == EstadoSalud.MUERTO )

		b : Buffer()
    then

        modify(martins){
			setUbicacion(Ubicacion.CEMENTERIO);
		}
		modify(calloway){
			setUbicacion(Ubicacion.CEMENTERIO);
		}
		
		modify(lime){
			setUbicacion(Ubicacion.CEMENTERIO);
		}
		

		modify(b){
			append(Personaje.martins+" y Calloway van a"+martins.getUbicacion().toString()+" al entierro de Lime. ");
		};

end

