package rules

import tercerhombre.personaje.Personaje;
import tercerhombre.propiedades.*;
import tercerhombre.io.Buffer;
import tercerhombre.Fin;

/*
* -------------------------------------------------------------------
* ######################## ALTERNATIVAS ############################
* -------------------------------------------------------------------
*/

rule "lime esta vivo y martins encuentra a lime" agenda-group "g0"
no-loop true
    when
        martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.CASALIME, estadoSalud == EstadoSalud.VIVO  )
        lime : Personaje( nombre == Personaje.lime, estadoSalud == EstadoSalud.VIVO )
        
       	b : Buffer()
    then

	modify(b){
		append(Personaje.martins+" encuentra a Lime y trabaja para él. ");
	};
	
	insert(new Fin());
    	
end

rule "martins muere" agenda-group "g0"
no-loop true
    when
    	martins : Personaje(nombre == Personaje.martins , estadoSalud == EstadoSalud.MUERTO  )
    
        b : Buffer()
    then
    	modify(b){
			append(Personaje.martins+" esta "+martins.getEstadoSalud()+". ");
		}
end

rule "karl muere" agenda-group "g0"
no-loop true
    when
    	karl : Personaje( nombre == Personaje.karl, estadoSalud == EstadoSalud.MUERTO  )
    
        b : Buffer()
    then
    	modify(b){
			append(Personaje.karl+" esta "+karl.getEstadoSalud()+". ");
			// TODO: como sigue ??
		}
end
        