//created on: 14-dic-2016
package rules

import tercerhombre.personaje.Personaje;
import tercerhombre.propiedades.*;
import tercerhombre.io.Buffer;


/*
 - Si Anna no es rusa no tiene problemas con el pasaporte y no la llevan a la comisaria.
 	Si no la llevan a la comisaria Martins va a su casa a hablar con ella
 	
 - Si Anna no es rusa, Martins no accede a ayudar a Calloway y decide irse a EEUU
 
*/

rule "Tumba Lime vacía" 

// **************** METADATOS ******************* //
  @ruleDate(2016-12-13)

  @ruleDescription("Al abrir la tumba de Lime está esta vacía.")

  @ruleAuthor(Jesús Garcerán)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //

agenda-group "g5"
salience 2
    no-loop true
    when
		martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.CLOACAS )
		calloway : Personaje (nombre == Personaje.calloway, ubicacion == Ubicacion.CLOACAS )
		harbin : Personaje (nombre == Personaje.harbin, ubicacion == null, estadoSalud == EstadoSalud.VIVO)

		b : Buffer()
    then

        modify(calloway){
			setUbicacion(Ubicacion.CEMENTERIO);
		}
		modify(martins){
			setUbicacion(Ubicacion.CEMENTERIO);
		}
		
		modify(harbin){
			setUbicacion(Ubicacion.HOSPITAL);
		}

		modify(b){
			append(Personaje.calloway+" y Martins van a"+calloway.getUbicacion().toString());
		};

		modify(b){
			append("La tumba de Lime está vacía.");
		};
end

rule "Anna no es rusa, Martins va a su casa a hablar de Lime" 

// **************** METADATOS ******************* //
  @ruleDate(2016-12-13)

  @ruleDescription("Si Anna no es Rusa, Anna no irá a la comisaría y Martins irá a su casa a decirle que ha visto a Lime.")

  @ruleAuthor(Jesús Garcerán)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //

agenda-group "g5"
no-loop true
    when
		martins : Personaje (nombre == Personaje.martins, ubicacion == Ubicacion.CEMENTERIO )
		calloway : Personaje (nombre == Personaje.calloway, ubicacion == Ubicacion.CEMENTERIO )
 		anna : Personaje (nombre == Personaje.anna, ubicacion == Ubicacion.CASAANNA, nacionalidad != Nacionalidad.AUSTRIA )
 		harbin : Personaje (nombre == Personaje.harbin, estadoSalud == EstadoSalud.MUERTO )
		lime : Personaje (nombre == Personaje.lime , estadoSalud == EstadoSalud.VIVO)
 		b : Buffer()
    then
    	modify(anna){
			setUbicacion(Ubicacion.CASAANNA);
		}
		
		modify(martins){
			setUbicacion(Ubicacion.CASAANNA);
		}
		modify(anna){
   		getBusca_a().add(lime);
		};
		
		modify(b){
			append(Personaje.martins+" va a"+martins.getUbicacion().toString()+" a hablar con Anna. ").
			append(Personaje.martins+" le cuenta a Anna que ha visto a Lime. ").
			append(Personaje.anna+" busca a Lime. ");
		};
    	
    	

end

rule "Anna no es rusa, Martins no ayuda a Calloway y se va" 

// **************** METADATOS ******************* //
  @ruleDate(2016-12-13)

  @ruleDescription("Si Anna no es rusa, Calloway no le puede dar nada a Martins a cambio de su ayuda, y Martins decide irse.")

  @ruleAuthor(Jesús Garcerán)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //


agenda-group "g5"
no-loop true
    when
		martins : Personaje (nombre == Personaje.martins, ubicacion == Ubicacion.COMISARIA )
		calloway : Personaje (nombre == Personaje.calloway, ubicacion == Ubicacion.COMISARIA )
 		anna : Personaje (nombre == Personaje.anna, nacionalidad != Nacionalidad.AUSTRIA )
 		
 		b : Buffer()
    then
    	modify(b){
			append(Personaje.martins+" no cede en ayudar a Calloway puesto que él no puede ofrecerle nada a cambio. ").
			append(Personaje.martins+" decide volverse a EEUU. ");
		};
    	
  
end


