//created on: 07-dic-2016
package rules

import tercerhombre.personaje.Personaje;
import tercerhombre.propiedades.*;
import tercerhombre.io.Buffer;


//TODO Revisar el orden de las reglas Y falta poner los append

rule "insertar anna, winkel,popescu,tercerhombre " 

// **************** METADATOS ******************* //
  @ruleDate(2016-12-04)

  @ruleDescription("Se insertan los personajes de los que hablan Kurtz y Martins. ")

  @ruleAuthor(Pablo Saura)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //

agenda-group "g2"
no-loop true

    when

    then

    // // System.out.println("XXX");
    	insert(Personaje.nuevo().
    	setNombre(Personaje.anna).
    	setGenero(Genero.MUJER).
    	setActividad(ActividadLegal.ACTRIZ).
    	setEstadoSalud(EstadoSalud.VIVO).
    	setNacionalidad(null).
    	setUbicacion(null));

    	//Insertamos a Winkel

    	insert(Personaje.nuevo().
    	setNombre(Personaje.winkel).
    	setGenero(Genero.HOMBRE).
    	setActividad(ActividadLegal.MEDICO).
    	setEstadoSalud(EstadoSalud.VIVO).
    	setNacionalidad(null).
    	setUbicacion(null));

		//insertamos popescu

    	insert(Personaje.nuevo().
    	setNombre(Personaje.popescu).
    	setGenero(Genero.HOMBRE).
    	setActividad(null).
    	setEstadoSalud(EstadoSalud.VIVO).
    	setNacionalidad(Nacionalidad.RUMANIA).
    	setUbicacion(null));

    	//insertamos tercerhombre

    	insert(Personaje.nuevo().
    	setNombre(Personaje.tercerhombre).
    	setGenero(Genero.HOMBRE).
    	setActividad(null).
    	setEstadoSalud(EstadoSalud.VIVO).
    	setNacionalidad(null).
    	setUbicacion(null));
    	
    	// System.out.println("insertar");

end

rule "martins van casa lime" 

// **************** METADATOS ******************* //
  @ruleDate(2016-12-04)

  @ruleDescription("Martins va a la casa de Lime para que Kurtz le explique como murió Lime. ")

  @ruleAuthor(Pablo Saura)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //

agenda-group "g2"
no-loop true
    when
    	martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.CAFEMOZART )
    	kurtz : Personaje( nombre == Personaje.kurtz, ubicacion == Ubicacion.CAFEMOZART )
    	b : Buffer()
    then

    // // System.out.println("XXX");
    	modify(martins){ //
		setUbicacion(Ubicacion.CASALIME);
		};
		
		modify(kurtz){ //
		setUbicacion(Ubicacion.CASALIME);
		};

		modify(b){
		append(Personaje.martins+" va a"+martins.getUbicacion().toString()+". ").
		append(Personaje.kurtz+" va a"+kurtz.getUbicacion().toString()+". ");
		}
		
		// System.out.println("martins va casa lime");
end


rule "kurtz y martins hablan de winkel" 

// **************** METADATOS ******************* //
  @ruleDate(2016-12-04)

  @ruleDescription("Kurtz y Martins hablan de que Dr Winkel estuvo en la muerte de Lime.")

  @ruleAuthor(Pablo Saura)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //

agenda-group "g2"
no-loop true
    when
    	martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.CASALIME )
        kurtz : Personaje( nombre == Personaje.kurtz, ubicacion == Ubicacion.CASALIME )
        winkel : Personaje( nombre == Personaje.winkel, estadoSalud == EstadoSalud.VIVO)
        lime : Personaje (nombre == Personaje.lime)
        popescu : Personaje (nombre == Personaje.popescu)
        karl : Personaje( karl == Personaje.karl)

        not Personaje( nombre == Personaje.winkel ) from kurtz.conoce_a

        b : Buffer()

    then

     // System.out.println("kurtz y martins hablan de winkel");
   		modify(winkel){//
    	 getConoce_a().add(lime);
    	};

		modify(winkel){//
    		getConoce_a().add(kurtz);
    	};

    	modify(winkel){// añadir en popescu
    		getConoce_a().add(popescu);
    	};

		modify(lime){//
    		getConoce_a().add(winkel);
    	};

    	modify(kurtz){ //
    		getConoce_a().add(winkel);
    	};

    	modify(b){
			append(Personaje.winkel+" conoce a "+Personaje.kurtz+". ").
			append(Personaje.winkel+" conoce a "+Personaje.lime+". ").
			append(Personaje.winkel+" conoce a "+Personaje.popescu+". ").
			append(Personaje.kurtz+" conoce a "+Personaje.winkel+". ").
			append(Personaje.lime+" conoce a "+Personaje.winkel+". ");
		}
		
		modify(karl){
    	 getConoce_a().add(kurtz);
    	};

    	modify(kurtz){
    	 getConoce_a().add(karl);
    	};

    	modify(b){
			append(Personaje.kurtz+" conoce a "+Personaje.karl+". ").
			append(Personaje.karl+" conoce a "+Personaje.kurtz+". ");
		}

end

rule "kurtz y martins hablan de popescu" 

// **************** METADATOS ******************* //
  @ruleDate(2016-12-04)

  @ruleDescription("Kurtz y Martins hablan de que Popescu estuvo en la muerte de Lime.")

  @ruleAuthor(Pablo Saura)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //

agenda-group "g2"
no-loop true
    when
    	martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.CASALIME )
        kurtz : Personaje( nombre == Personaje.kurtz, ubicacion == Ubicacion.CASALIME )
        winkel : Personaje( nombre == Personaje.winkel)
        lime : Personaje (nombre == Personaje.lime)
        popescu : Personaje (nombre == Personaje.popescu,estadoSalud == EstadoSalud.VIVO)
        karl : Personaje( karl == Personaje.karl)

        not Personaje( nombre == Personaje.popescu ) from kurtz.conoce_a

        b : Buffer()

    then

     // System.out.println("kurtz y martins hablan de popescu");

    	modify(lime){ //
    		getConoce_a().add(popescu);
    	};

    	modify(lime){ //
    		getAmigo_de().add(popescu);
    	};

    	modify(popescu){//
    		getConoce_a().add(lime);
    	};

		modify(popescu){//
    		getAmigo_de().add(lime);
    	};

		modify(popescu){//
    		getConoce_a().add(kurtz);
    	};

		modify(popescu){//
    		getAmigo_de().add(kurtz);
    	};

    	modify(popescu){//
    		getConoce_a().add(winkel);
    	};

		modify(kurtz){ //
    		getConoce_a().add(popescu);
    	};

    	modify(kurtz){//
    		getAmigo_de().add(popescu);
    	};

    	modify(b){
			append(Personaje.popescu+" conoce a "+Personaje.winkel+". ").
			append(Personaje.popescu+" conoce a "+Personaje.lime+". ").
			append(Personaje.popescu+" conoce a "+Personaje.kurtz+". ").
			append(Personaje.popescu+" es amigo de "+Personaje.lime+". ").
			append(Personaje.popescu+" es amigo de "+Personaje.kurtz+". ").
			append(Personaje.lime+" es amigo de "+Personaje.popescu+". ").
			append(Personaje.lime+" conoce a "+Personaje.popescu+". ").
			append(Personaje.kurtz+" conoce a "+Personaje.popescu+". ").
			append(Personaje.kurtz+" es amigo de "+Personaje.popescu+". ");
		}
		
		modify(karl){
    	 getConoce_a().add(kurtz);
    	};

    	modify(kurtz){
    	 getConoce_a().add(karl);
    	};

    	modify(b){
			append(Personaje.kurtz+" conoce a "+Personaje.karl+". ").
			append(Personaje.karl+" conoce a "+Personaje.kurtz+". ");
		}
end

rule "kurtz y martins hablan de anna" 

// **************** METADATOS ******************* //
  @ruleDate(2016-12-04)

  @ruleDescription("Kurtz y Martins hablan de que Anna era la novia de Lime.")

  @ruleAuthor(Pablo Saura)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //


agenda-group "g2"
no-loop true
    when
    	martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.CASALIME )
        kurtz : Personaje( nombre == Personaje.kurtz ,ubicacion == Ubicacion.CASALIME )
        anna : Personaje( nombre == Personaje.anna, estadoSalud == EstadoSalud.VIVO)
        lime : Personaje (nombre == Personaje.lime)
        karl : Personaje( karl == Personaje.karl)
        
        not Personaje( nombre == Personaje.anna ) from kurtz.conoce_a 
         
        b : Buffer()

    then

     // System.out.println("kurtz y martins hablan de anna");

    	modify(kurtz){ //
    		getConoce_a().add(anna);
	    };

    	modify(lime){//
    		getConoce_a().add(anna);
	    };

	    modify(anna){ //
			setUbicacion(Ubicacion.CASANOVACLUB);
		};

		modify(anna){ //
    		getConoce_a().add(lime);
	    };

   		modify(martins){ //
    		getBusca_a().add(anna);
    	};

    	modify(b){
			append(Personaje.lime+" conoce a "+Personaje.anna+". ").
			append(Personaje.kurtz+" conoce a "+Personaje.anna+". ").
			append(Personaje.anna+" conoce a "+Personaje.lime+". ").
			append(Personaje.anna+" está en "+anna.getUbicacion().toString()+". ").
			append(Personaje.martins+" busca a "+Personaje.anna+". ");
		};
		
		modify(karl){
    	 getConoce_a().add(kurtz);
    	};

    	modify(kurtz){
    	 getConoce_a().add(karl);
    	};

    	modify(b){
			append(Personaje.kurtz+" conoce a "+Personaje.karl+". ").
			append(Personaje.karl+" conoce a "+Personaje.kurtz+". ");
		}

end

/*
*
* ESTA ES LA REGLA DEL BUCLE ↓↓↓↓↓
* 
*/

/*
rule "kurtz y martins hablan con karl" agenda-group "g2"
no-loop true
    when
    	martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.CASALIME )
        kurtz : Personaje( nombre == Personaje.kurtz,ubicacion == Ubicacion.CASALIME )
        karl : Personaje( karl == Personaje.karl)

		not Personaje( nombre == Personaje.karl ) from kurtz.conoce_a    

        b : Buffer()

    then

   		modify(karl){
    	 getConoce_a().add(kurtz);
    	};

    	modify(kurtz){
    	 getConoce_a().add(karl);
    	};

    	modify(b){
			append(Personaje.kurtz+" conoce a "+Personaje.karl+". ").
			append(Personaje.karl+" conoce a "+Personaje.kurtz+". ");
		}

		// System.out.println("kurtz y martins hablan con karl");
end
*/

rule "visita a anna en el teatro" 

// **************** METADATOS ******************* //
  @ruleDate(2016-12-04)

  @ruleDescription("Martins decide visitar a Anna en el teatro para conocerla.")

  @ruleAuthor(Pablo Saura)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //


agenda-group "g2" //
no-loop true
	when
    	martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.CASALIME )
    	anna : Personaje( nombre == Personaje.anna ,estadoSalud == EstadoSalud.VIVO, ubicacion == Ubicacion.CASANOVACLUB)
    	lime : Personaje( nombre == Personaje.lime)
    	b : Buffer()
    then

    // System.out.println("visita a anna en el teatro");

     	modify(martins){
	    setUbicacion(Ubicacion.CASANOVACLUB);
	    };

	     modify(martins){
	    		getConoce_a().add(anna);
	    };

	    modify(anna){
	    		getConoce_a().add(martins);
	    };

	    modify(anna){
    		getQuiere_a().add(lime);  //TODO sabemos si lime quiere a anna?
    	};

    	modify(b){
			append(Personaje.martins+" va a"+martins.getUbicacion().toString()+". ").
			append(Personaje.martins+" conoce a "+Personaje.anna+". ").
			append(Personaje.anna+" conoce a "+Personaje.martins+". ").
			append(Personaje.anna+" quiere a "+Personaje.lime+". ");
		};

end

 rule "vuelta a casa Lime" 
 
 // **************** METADATOS ******************* //
  @ruleDate(2016-12-04)

  @ruleDescription("Kurtz y Anna vuelven a la casa de Lime para hablar con el portero Karl.")

  @ruleAuthor(Pablo Saura)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //
 
 
 agenda-group "g2"
 no-loop true
	when
    	martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.CASANOVACLUB )
        anna : Personaje( nombre == Personaje.anna ,estadoSalud == EstadoSalud.VIVO,ubicacion == Ubicacion.CASANOVACLUB)
        karl : Personaje( nombre == Personaje.karl )
        tercerhombre : Personaje ( nombre == Personaje.tercerhombre )
        b : Buffer()
    then

    // System.out.println("vuelta a casa Lime");

    	modify(martins){
	    setUbicacion(Ubicacion.CASALIME);
	    };
	    modify(anna){
	    setUbicacion(Ubicacion.CASALIME);
	    };
	    modify(anna){
	    		getConoce_a().add(karl);
	    };
	    modify(karl){
	    		getConoce_a().add(anna);
	    };
	     modify(martins){
	    	getBusca_a().add(tercerhombre);
	    };
	    modify(b){
			append(Personaje.martins+" va a"+martins.getUbicacion().toString()+". ").
			append(Personaje.anna+" va a"+martins.getUbicacion().toString()+". ").
			append(Personaje.anna+" conoce a "+Personaje.karl+". ").
			append(Personaje.karl+" conoce a "+Personaje.anna+". ").
			append(Personaje.martins+" Busca a "+Personaje.tercerhombre+". ");
		};



end

rule "martins y anna van a casa de anna" 

// **************** METADATOS ******************* //
  @ruleDate(2016-12-04)

  @ruleDescription("Martins y Anna se dirigen a la casa de Anna a hablar.")

  @ruleAuthor(Pablo Saura)

  @ruleVersion(1.0.0)
// **************** FIN METADATOS ******************* //


agenda-group "g2"
no-loop true
	when
    	martins : Personaje( nombre == Personaje.martins, ubicacion == Ubicacion.CASALIME )
      	anna : Personaje( nombre == Personaje.anna, estadoSalud == EstadoSalud.VIVO, ubicacion == Ubicacion.CASALIME)

      	b : Buffer()
    then

	// System.out.println("martins y anna van a casa de anna");

    	modify(anna){
	    setUbicacion(Ubicacion.CASAANNA);
	    };
	    modify(martins){
	    setUbicacion(Ubicacion.CASAANNA);
	    };


	    modify(b){
			append(Personaje.martins+" va a"+martins.getUbicacion().toString()+". ").
			append(Personaje.anna+" va a"+martins.getUbicacion().toString()+". ");
		};


end
