package tercerhombre.propiedades;

public enum Ubicacion {
	PLAZA, CASALIME, CASAANNA, HOTELSACHER, TEATROJOSEPH, 
	CASANOVACLUB, CONFERENCIA, CASAWINKEL, SECTORRUSO, 
	CAFEMARC, COMISARIA, CEMENTERIO, CAFEMOZART, 
	FUERADEVIENA, NORIA, PUB, CLOACAS
}
